pyta-uoft/pyta

- examples/global_variables_test.py
- global_variables_checker.py
Modified the global variables checker so that it throws an error when top-level variables are declared and used.
> Top level global variables

- pyta.py
Now, it should be possible to re-check the same file after having made a change, and see the change reflected in PyTA's output. (Before, the AST of the module was being cached by astroid, so no changes were noticed until the Python shell was restarted.)
> Invalidate astroid cache before each check

- examples/README.md
The pyta/examples/ directory should have a readme file to explain the format of examples, with the purpose of standardizing the examples.
> Issue 62 examples readme

- examples/pylint/E0102_function_redefined.py
i don't know why this example is used, but it had an annoying mistake.
> fixed example that was weird

- python_ta/transforms/type_inference_visitor.py
- tests/type_inference/type_inference_visitor_unittest.py
BinOp Components: 
- Supports List/Tuple/String Concatenation using `+` or `*` operators.
- Operators includes `+,  -,  *,  /,  **,  //,  %`.
- Raise `ValueError` exception when invalid operations are detected, for instance, `'abc' * 'sss`, `[1, 2] * [3, 4]`.
Other Node Types:
- Compare Node
- Subscript Node
- List, Tuple, Dict Node
- Const Node
- UnaryOp Node
> typecheck: Type Constraints

- python_ta/__init__.py
- python_ta/patches/__init__.py
- python_ta/patches/checkers.py
- setup.py
This changes the behaviour of the pylint check W0212 (protected-member-access), to **allow** all protected instance attributes of a class to be accessed from within methods of that class. By default, only `self`, was allowed to access this.
> pylint-patch: protected-member-access

- python_ta/checkers/IO_Function_checker.py
- python_ta/checkers/always_returning_checker.py
- python_ta/checkers/assigning_to_self_checker.py
- python_ta/checkers/dynamic_execution_checker.py
- python_ta/checkers/forbidden_import_checker.py
- python_ta/checkers/global_variables_checker.py
- python_ta/checkers/invalid_range_index_checker.py
- The name of a checker is the same as its file name but without the _checker part (underscore is used for name).
-  Dashes are used for connecting words in a message symbol.
- The parameter of decorator function check_messages() is the message symbol.
> fixed naming inconsistency

- sample_usage/pyta_stats.py
This fixes the problem pointed out by @rebeccakay where a non-nested directory of student files would not run correctly (stats would not be calculated since the module could not be found). It was a simple (yet again) PYTHONPATH problem that has now been fixed.
> Fix single-student stats problem

- nodes/Import.py
- nodes/ImportFrom.py
- nodes/Index.py
- nodes/TODO.md
I've finished fixing the documentations for the last three nodes (Import, ImportFrom, Index).
I also deleted those three nodes from TODO.md.
Side Notes: 
One interesting thing that I found was that Import and ImportFrom don't have any attributes in the astroid fields (their attributes are in _other_fields); therefore, when I tried printing the astroid node tree for Import and ImportFrom, it showed that there weren't any attributes for those nodes. I needed to use the debugger in order to see more details about their attributes.
> Node-docs-TODO last three nodes

- python_ta/reporters/TODO.md
- python_ta/reporters/color_reporter.py
- python_ta/reporters/html_reporter.py
The following suggested changes were completed (numbering consistent with ROP A4 feedback page):
1. The overall formatting of the ColorReporter output takes up too much vertical space per error message. Work on reducing the number of blank lines that appear. Consider reducing indentation of text output to 2 spaces instead of 4. **(removed most blank lines, reduced indent)**
2. The heading "Your Code Starts Here" should not have every word capitalized. Moreover, I don't actually think this heading is necessary at all in either reporter type. It should be pretty clear based on formatting which parts are the student code. **(removed heading)**
3. The style of bolding in ColorReporter doesn't match the logical structure of headings. For example, the short name of the message (e.g., …
> Make some suggested amendments to reporters and add to TODO

- python_ta/__init__.py
We can now pass a keyword argument, a dict of config options, to `check_all()` or `check_errors()`.
An example of the dict of config options is:
```python
CONFIG = {
'max-nested-blocks': 3,
'max-line-length': 80,
'allowed-import-modules': ['doctest', 'unittest', 'hypothesis', 'python_ta'],
'allowed-io': None,
'disable': ['R0401', 'R0901', 'R0903', 'R0904', 'R0911', 'R0916', 'W0402', 
'W0403', 'W0410', 'W1501', 'W1502', 'W1505', 'E1300', 'E1301', 
'E1302', 'E1304', 'W1300', 'W1301', 'W1302', 'W1304', 'E1124', 
'E1125', 'E1129', 'E1132', 'W1402', 'W0105', 'E1303', 'W1306', 
'W1307', 'E0116', 'E0114', 'E0112', 'E0115', 'E0106', 'E0113', 
'E0111', 'E0105', 'E0100', 'E0117', 'W0150', 'W0120', 'W0124', 
'W0108', 'W0123', 'W0122', 'W0110', 'C0122', 'C0200', 'W0141', 
'W0640', 'W0623', 'W0614', …
```
> Add to _check() API to accept a dict of config options for Checkers.

- python_ta/transforms/type_inference_visitor.py
- tests/type_inference/test_literals.py
- Extend Name node visitor to properly set type constraints for multi-assignment statements
(ie. a = b= 3)
- Add test case for aforementioned type of statements.
> Dev test multi assignment statement

- tests/type_inference/test_functions.py
- Add test case for programs that contain function definitions with parameter(s) that returns one of it's arguments.
- Add test case for programs containing function definitions mentioned above, but with a single function call afterwards.
> Implement test cases for programs containing function definitions

- python_ta/checkers/global_variables_checker.py
The `nodes/Break.py` example was triggering the E9997 error from
the global variable checker. For instance the range() call, which
should be allowed.
> Allow the Name node to pass the checker.

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- python_ta/typecheck/type_store.py
- tests/type_inference/test_function_def_inference.py
- Refactor imports; TYPE_CONSTRAINTS singleton is passed as attribute of TYPE_STORE to prevent circular import.
- Implement helper to check whether types can be unified without mutating; update function look-up method accordingly.
- Test whether type of argument/function are being inferred correctly given functions in the function body.
> Function def inference

- python_ta/__init__.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/plain_reporter.py
- python_ta/reporters/templates/template.txt
• Output the html file in current working directory.
• Display all files' messages in htmlreporter, when linting done on a directory. Previously multiple files unsupported by htmlreporter.
> Output htmlreporter recursive linting

- python_ta/patches/messages.py
- python_ta/reporters/node_printers.py
- python_ta/reporters/plain_reporter.py
• Add snippets to messages for C0326 bad-whitespace, C0301 line-too-long. Add `msg_truncated` attribute to namedtuple object. Print message from the `msg.msg_truncated` property now.
• Fix off by one error on line 68, that would wrap around to the last [-1] line and display it as line 0.
• R1705 `no-else-return` was missing some lines, and double counting others. This fix makes the snippet great again.
• Also fixes C0330 to remove redundant ` }\n| |^` from message output.
> Create snippets for messages C0326, C0301, and fix R1705.

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/custom_hypothesis_support.py
- tests/type_inference/test_subscript.py
- Implement visitor for Slice node.
- Register Slice node visitor
- Extend eval_type for Generics; works for all Generics using _gorg
- Add test cases for Subscript node representing List slices.
- Add helper to return strategy for generating slice indices.
> Dev test slice

- python_ta/transforms/setendings.py
This went unnoticed 4 months ago. As a bonus, this change improves runtime, noticeable when running nosetests.
> Fix indentation. 

- python_ta/reporters/plain_reporter.py
When the number of messages is limited in config, `pyta-number-of-messages`, the indication was falling below in to the next line. Fixed.
Old,
```
C0111 (missing-docstring)  Number of occurrences: 4.
First 2 shown.  [Line 1] Missing module docstring
<omitted>
[Line 1] Missing function docstring
```
New,
```
C0111 (missing-docstring)  Number of occurrences: 4. (First 2 shown).
[Line 1] Missing module docstring
<omitted>
[Line 1] Missing function docstring
```
> Prevent message line from falling down into next line.

- python_ta/.pylintrc
- python_ta/__init__.py
- python_ta/reporters/__init__.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/plain_reporter.py
- python_ta/reporters/position_reporter.py
Add reporter that outputs JSON formatted messages for each file linted in the call to `python_ta.check`.
The main purpose is for the 4 locations, `lineno, end_lineno, col_offset, end_col_offset`.
Notes:
• code "snippets" are currently not provided, as this may not be needed for the intended use.
• for now, `skipped` files ignored in the JSON unless we want to store this information in the reporters and change in our plain/color/html/position reporters in a future commit.
```
self._output = {   
'total_skipped': 0,
'skipped': []
}
```
• `NewMessage` messages without a `node` attribute don't have location data. For now the location of the whole line is used. TODO: use more accurate location data. [See some message-specific policies set `start` and `stop` locations in `node_printers.py`.]
> Add positionreporter

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/type_inference/test_assignments.py
- tests/type_inference/test_binops.py
- tests/type_inference/test_boolops.py
- tests/type_inference/test_functions.py
- tests/type_inference/test_subscript.py
- tests/type_inference/test_unaryops.py
- Reimplement test cases using properties of AST instead of calling type.
- Update can_unify and unify to account for special cases: when type is Any, Union, or TypeErrorInfo
- Update UnaryOp visitor to raise KeyError when method not found as in Bin/BoolOp Visitors (Decided to make change in same branch because I wanted this branch to deal with making sure all test cases were implemented correctly along with changes to allow them to pass.)
- Will reimplement test case for Assignments in that branch since PR is already open.
> Fix old tests

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_assignments.py
- tests/test_type_inference/test_for.py
- tests/test_type_inference/test_literals.py
- tests/test_type_inference/test_subscript.py
- Implement helper to return least general unifier of two types.
- Update List, Dict, Set node visitors to use helper and set type constraints.
- Update test cases assumptions (bool and int unified).
> Reimplement iterables visitors

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_classdef.py
- Set type constraint of ClassDef node to be NoType.
- Add to Assign node visitor to handle AssignAttr nodes to properly unify instance attributes.
- Add TODOs to deal with bad unify Exception arising from trying to unification when
1. calling __init__ function during instantiation.
2. assigning to an attribute that's already been assigned a different type.
- Fix whitespace formatting.
> Dev test classdef

- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_function_def_inference.py
- Add strategy to generate annotations. 
- Extend FunctionDef node visitor to handle function definition annotations.
- Add test case for function definition annotations.
> Dev test functiondef annotation

- python_ta/patches/messages.py
- python_ta/patches/type.py
This change allows our transforms to handle the case when a syntax error causes the original `PyLinter.get_ast` method to return `None`.
> Fix ast patches when there is a syntax error

- python_ta/reporters/color_reporter.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/plain_reporter.py
- python_ta/reporters/templates/script.js
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
Decided to go with the backend syntax formatter (pygments) after trying other frontend solutions (highlightjs, prismjs).
- Changed pluralization of occurances
- remove nbsp and br,
- made more responsive (frontend stuff)
- line numbers more different
- fixed parent container jitter
- syntax highlighting
- configure number_of_messages to work with htmlreporter
> Htmlreport pygments

- python_ta/checkers/forbidden_import_checker.py
Useful to not override (or restate) existing whitelist of imports,
which include python_ta, typing, and testing libraries.
> Add new option extra-imports.

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_compare.py
- tests/test_type_inference/test_functions.py
- Update op_to_binary dictionary to help return more natural error messages.
- Implement the basic case for a "hints" dictionary, that will supplement error messages in the hopes of guiding students to a possible solution.
- Implement test case for type inference error when calling the binary operator for addition on incompatible types.
- Update the error message returned for aforementioned error to be more informative and natural.
*** Added TODOs for where there could be improvements in making return message more natural.
> Error messages

- tests/custom_hypothesis_support.py
- Use draw function instead of example function to properly generate nodes.
- Deprecation warnings have been resolved.
> Fixed deprecation warnings.

- python_ta/typecheck/README.md
- python_ta/typecheck/errors.py
- tests/test_type_inference/test_functions.py
- Add section for unary operation error messages.
- Add test case for a built-in unary operator being called on an argument of the wrong type.
> Error messages unaryop

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- tests/test_type_inference/test_assign_tuple.py
Adding error cases to type_inference_visitor for assigning tuples of different length, assigning a single value to multiple variables, and assigning multiple values to a single value
Adding test files for all tuple assignment errors cases
Added line to _assign_type to check for TypeFail when attempting to turn a non-tuple into an iterable
> typecheck: fixing assignment of tuples of different lengths

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- python_ta/typecheck/base.py
- tests/test_type_inference/test_functions.py
Fixing type signature of unify_call, as well as all relevant functions that use it
> Typecheck: Fix unify call return type

- python_ta/typecheck/base.py
- tests/test_type_constraints/test_unify.py
Also added two tests for polymorphic function calls.
> typecheck: Fix unify returning unresolved types on higher-order calls

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_classdef.py
Removing instances of TypeInferenceError in `_handle_call`, `visit_attribute`, `unify_call`
Updated test that was originally raised SkipTest from an TypeInferenceError exception, now just raises SkipTest automatically
> typecheck: removing outdated TypeInferenceError

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- tests/test_type_inference/test_initializer.py
`visit_call` checks for an `__init__` function, and if there is none, creates a callable with the same type signature that an initialization function would have, to be passed to `unify_call`
> Typecheck: handling classes without initalizer

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_function_overload.py
Editing `visit_functiondef` to check for optional arguments, and assign a `Union` of different possible type signatures as the inferred type of that `FunctionDef node`
Editing `unify_call` to handle being passed a `Union` of `Callable`s
Adding test cases for overloaded functions
Planning to make additional changes to `type_store` to handle this representation of this representation of type signatures, will include in separate pull request
> Typecheck: Overloaded functions

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assign_tuple.py
Added lines to `visit_assign` to properly set `inf_type` in the case of a type failure
Change return type of `_assign_type` to return a TypeResult
Separated tests in `test_assign_tuple` for tuples of different types
> Typecheck: Checking inferred values of variables during re-assignment

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assign_tuple.py
Previously treated assigning a tuple to a single variable as an error, however this should be valid python code
> Typecheck: assigning tuple to single variable

- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_classdef.py
- tests/test_type_inference/test_initializer.py
Added proper error checking in `visit_call`
Edited `visit_attribute` to account for TypeFail objects, which do not have a `__name__` attribute
Added new test to `test_initializer`
Added `reset` function to `type_inference_visitor` to reset TypeStore, edited `_parse_text` to include a flag for resetting before parsing text
Edited tests in `test_classdef` to make use of `reset` (information from previous tests was being carried over)
> Typecheck: __init__ with multiple arguments

- python_ta/typecheck/README.md
- python_ta/typecheck/base.py
Change type annotation of _nodes to reflect its actual type, list of _TNodes, rather than a list of sets of _TNodes
> Changing type annotation of _nodes

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_subscript.py
I have assumed, as before, that inferred type for a Subscript node within an Assign node (ctx=Store) is NoneType (the return type of \_\_setitem\_\_), but I'm not sure if this is the case. It might make more sense if the whole Assign node is handled as a call to \_\_setitem\_\_ so that Assign.value can be passed as the last argument of \_\_setitem\_\_ (and this also fits in with Assign nodes being of type NoneType). But this means treating this case as a special case in visit_assign. The inferred type of the Subscript node itself would be the type of Assign.value (or a list around that type in case of a slice).
> typecheck: Fix call in visit_subscript & add tests

- python_ta/typecheck/base.py
Adding proper behavior for attempting to unify two of the same variable where both variables are not concrete
> typecheck: Unifying TypeVar with itself

- python_ta/typecheck/base.py
- tests/test_type_inference/test_function_def_inference.py
Resolve now returns a set representative if a concrete typ…e cannot be found. Unifying two typevars with no parents now consistently returns one TypeVar
> typecheck: Resolve now returns a set representative

- python_ta/transforms/type_inference_visitor.py
Currently, both `a = A()` and `a = A` (where `A` is a class) lead to `a` being inferred as a `_ForwardRef('A')`. However, the latter case should result in `a` being inferred as `Type[_ForwardRef('A')]` becase it is a class and not an instance of a class.
> typecheck: Fix wrong type assigned to classes

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- tests/test_type_inference/test_subscript.py
I remember that we talked about there not being a need to visit `ExtSlice` nodes. I could move the code in `visit_extslice` to be handled as a case in `visit_subscript` if it's a problem that `ExtSlice` nodes are assigned types.
> typecheck: Handle ExtSlice in Subscript nodes

- nodes/Name.py
Changed Name node attribute from "id" to "name". 
astroid.Name.id (wrong) -> astroid.Name.name (correct)
> Correct documentation for Name.py

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
Adding decorator to allow functions to optionally take Failables as arguments, returning the Failable if it is a TypeFail
Updating several visit functions in type_inference_visitor to pass TypeResults directly to unify, rather than using .getValue()
Creating helper functions for common functionality between these visit functions
> typecheck: Decorator for functions to take Failables as arguments

- python_ta/typecheck/base.py
- tests/test_type_constraints/test_tnode_structure.py
`can_unify` has been reimplemented so that it makes a copy of the current TypeConstraints object and calls unify on the copy so as to avoid modifying the original TypeConstraints. This is inefficient, but my previous implementation was short-sighted and caused problems throughout. The added test case (which previously failed at the assert line) demonstrates the necessity of this change.
To make things more efficient, I could use a hybrid approach: the previous method always ~~fails~~ passes when it should, so a copy would be necessary only to verify a success (most calls to can_unify result in failures anyway). Alternatively, I could hard-code some common cases that allow us to bypass the general check.
> typecheck: Reimplement can_unify to fix incorrect behavior

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- python_ta/typecheck/type_store.py
- tests/test_type_inference/test_attribute.py
The dictionaries in TypeStore now have tuples as their values: the first item is the type signature of the function, as before, and the second item is the the method type ('method', 'classmethod', 'staticmethod') in case of a method or 'attribute' otherwise. This allows `visit_attribute` to not trim off the first argument in static methods.
> typecheck: Modify TypeStore to allow proper method type differentiation in visit_attribute

- python_ta/transforms/type_inference_visitor.py
This change makes type inference for calls to builtin class initializers consistent with the behavior for user-defined classes (and the case directly below the change).
> typecheck: Fix inferred type for calls to initializer functions

- tests/test_type_constraints/test_tnode_structure.py
Otherwise, we can't test sets containing _ForwardRefs, etc.
> typecheck: Add better set comparison in test_tnode_structure

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_assign_tuple.py
- tests/test_type_inference/test_subscript.py
Replacing TypeInfo(NoType) with NoType, now a subclass of TypeResult, moved to base.py
> typecheck: Replacing TypeInfo(NoType)

- python_ta/typecheck/base.py
- tests/test_type_inference/test_tnode_structure.py
- tests/test_type_inference/test_typefail_reason.py
Adding TypeFail subclass `TypeFailUnify` with `get_reasons()` function, to be used by checkers and reporters to generate comprehensive error messages
Adding `find_path` function to `_TNode`, to be used by `get_reasons()` to find a chain of type inferences
Modifying `_find_type_fail` in test_tnode_structure.py to be used by other test files
Adding relevant test cases
> typecheck: Adding TypeFailUnify subclass and relevant tests

- python_ta/transforms/type_inference_visitor.py
Removing accidental case attempting to call `lower()` on a `None` object
> typecheck: Small fix to logic in get_attribute_class

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- python_ta/typecheck/type_store.py
- sample_usage/draw_tnodes.py
- tests/test_type_constraints/test_tnode_structure.py
- tests/test_type_constraints/test_unify.py
I am currently looking into the astroid source code for mro() which seems to be discarding subscripted classes like `SupportsAbs[int]`. Ideally, we shouldn't have to store both `__bases` and `__mro` in the classes dictionary.
> typecheck: Initiate support for inheritance

- python_ta/typecheck/base.py
- tests/test_type_inference/test_typefail_reason.py
Adding subclass for type inference errors specifically related to type annotations, as students will be required to annotate often. Only supports annotation errors in assignment based operations so far, waiting on some pending changes to `visit_call` before modifying
> typecheck: Adding subclass TypeFailAnnotation

- tests/test_type_inference/test_function_overload.py
Fixing minor error in test case, should not be using unbound identifier
Error discovered while working on changing lookup_typevar to be monadic
> typecheck: Removing unbound identifier in test case

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assign.py
Changing lookup_typevar to return a TypeInfo or TypeFail, thereby fixing crashes caused by nodes/Call.py and nodes/Assign.py
Updating test case in test_binops to use failable_collect
This replaces pull request #450 and #452
> typecheck: Modifying lookup_typevar to be monadic

- python_ta/typecheck/errors.py
Change prompted by `examples/pyling/c0121_single_comparison.py`
> typecheck: Resolving case of non-types passed to _get_name in errors.py

- python_ta/transforms/type_inference_visitor.py
Prompted by crash in `examples/pylint/E0211_no_method_argument.py`
> typecheck: Resolving crash caused by no method argument

- python_ta/transforms/type_inference_visitor.py
Prompted by crash in `examples/pylint/E0241_duplicate_bases.py`
> typecheck: Resolving crash caused by duplicate bases

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_functions.py
Add check for non-callable objects in `get_call_signature`, and add relevant test case
Change prompted by `examples/pylint/E1102_not_callable.py`
> typecheck: Implementing TypeFailFunction for non-callable objects

- python_ta/typecheck/base.py
Fixing crash in nodes/Arguments.py, when an argument is annotated with a string literal, as opposed to the str type
> typecheck: Adding case in _node_to_type for astroid.Const node

- .travis.yml
- setup.py
Prompted by releases of astroid 2.0 and pylint 2.0 on July 15, 2018
First noticed during Travis CI build of #454
> typecheck: Editing required astroid and pylint versions

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_assign_tuple.py
- tests/test_type_inference/test_starred.py
First noticed while fixing crash in nodes/Starred.py
Adding support for assigning tuples, lists and iterators to a tuple with a starred variable
> typecheck: Adding support for assignment to Starred variables

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
Removing unification of function type with function type annotations in `visit_functiondef`, as that is now taken care of in `visit_arguments`
Some changes made to `visit_arguments` and `visit_return` to solve for cases that had previously been handled in `visit_functiondef`. `visit_arguments` now unifies parameters without annotations with `Any` and `visit_return` now checks for a return type annotation. Both of these were previously indirectly handled by the `parse_annotations` call in `visit_functiondef`
These changes also reveal an unrelated error in `test_classdef.test_classdef_method_call`, caused by an incorrect `TypeFailLookup` in the return statement of `get_name`. This error should be resolved by fixes in @simeonkr's #477
> typecheck: Removing redundant function type annotation

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
Removing `_closest_frame` function, instead finding scope directly in `lookup_typevar`.
`lookup_typevar` also directly searches TypeStore if variable is found to be a builtin (behaviour previously handled by `isinstance(TypeFail` checks in `visit_name`)
Other functions have been modified to remove their dependency on `_closest_frame`
> typecheck: Replacing _closest_frame

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- tests/test_type_inference/test_functions.py
Also moving initializer logic in `get_call_signature` so that it is only invoked when a Class type is called
> typecheck: Adding support for __call__ magic method

- examples/type_annotation_example.py
Prompted by unnecessary instances of TypeFailLookup when running type inference checker (trying to keep this example to purely annotation errors)
> typecheck: Slight edits to type_annotation_example

- python_ta/transforms/type_inference_visitor.py
Prompted by errors caused when return statement in a function def is within an expression, such as if statements
> typecheck: Fixing functiondef lookup in visit_return

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
Excepting imported objects from being added to type environment
Prompted by issues caused by code such as the following:
```
from typing import Dict
var: Dict[str, int]
```
In previous implementation, `Dict` would be assigned a type variable, causing incorrect behaviour when `lookup_inf_type` was called while visiting the `Name.Dict` node in the annotation expression
> typecheck: Excepting imported objects from being added to type environment

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- python_ta/typecheck/base.py
- tests/test_type_inference/test_annassign.py
- tests/test_type_inference/test_function_annotation.py
Prompted by errors raised when running type inference checker on student code for CSC 148, specifically
```
_cars: Dict[str, 'Car']
```
Does not yet support unspecified multi-parameter Tuple annotation, ie. if a variable is annotations as `Tuple`, then it will only unify with single-parameter tuples
> typecheck: Adding support for generic type annotations with subscripts

- python_ta/typecheck/base.py
- python_ta/typecheck/type_store.py
- tests/test_type_constraints/test_tnode_structure.py
This change allows unification of types like `List[int]` and `Sequence[~_T]`.
> typecheck: Handle inheritance for generic types properly

- examples/type_annotation_example.py
- python_ta/checkers/type_annotation_checker.py
Fixing logic in `for attr_node in node.locals`, was previously raising false positives. Previous type annotation example only checked that missing annotations were pointed out, and variables with correct annotations were also classified as missing annotations. For example, `class_var: int = 0` and `class_var: int` would previously be highlighted as missing a type annotation. 
Also now requires instances variables to be annotated in class body. type_annotation_example edited to provide example
> typecheck: Fixing type_annotation_checker

- tests/test_type_constraints/test_tnode_structure.py
I changed the method used in the test only because the old one had * args.
> typecheck: Unskip test in test_tnode_structure

- python_ta/transforms/type_inference_visitor.py
Prompted by `AttributeError` raised when attempting to look up type variable for target when target does not have `name` attribute, ie.
```
def __init__(self):
self.attr: int
```
> typecheck: Adding support for attribute type annotation

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_initializer.py
Moved unification of class name with class type into environment transformer, so that instantiations of classes that are defined later in the code are considered valid
> typecheck: Moving unification of class type to environment transformer

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assign_tuple.py
Prompted by errors raised when testing on student code that assigned to multiple variables in one line, when those variables were elements or attributes
> typecheck: Adding support for assigning to tuples of subscripts and attributes

- python_ta/transforms/type_inference_visitor.py
Errors caused when target_type is referenced before assignment
> typecheck: Ensuring 'target_type' is assigned in visit_augassign

- python_ta/transforms/type_inference_visitor.py
Prompted by crashes when return statement is not in function, thus `node.scope()` returns a node that does not have a `returns` attribute
> typecheck: Modifying visit_return to use get_attr

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_for.py
Fixing call to `wrap_container` so a list of subtarget inferred types is passed in as an argument, rather than a generator
Adding test cases for iterating through lists of tuples, dictionaries, and zipped lists. Tests cases for dictionaries and zipped lists are skipped for now, for reasons detailed below
> typecheck: Fixing call to wrap_container in visit_for

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assign_tuple.py
- tests/test_type_inference/test_starred.py
Moving functionality previously in `_assign_tuple` to helper function, so that it can be used by `_assign_type` when assigning a variable value to tuple of variable targets. This allows `_assign_type` to handle assigning to tuples that contain `AssignAttr` or `Subscript` nodes
Adding check for multiple starred variables, when assigning a variable value to tuple of variable targets
Adding test cases for assigning to tuple of attributes, and assigning to multiple starred variables
Fixing typo in `test_starred` where inferred type of name nodes is not being properly checked
> typecheck: Adding helper function for assigning to tuple of variables, check for multiple starred variables in assignment

- python_ta/typecheck/base.py
- tests/test_type_constraints/test_tnode_structure.py
Changing name of type variables to better distinguish between the ones generated by the type inference checker, and the polymorphic type variables included in typeshed
Specifically, `get_poly_vars` would often inadvertently include `~_T1` and `~_T2` as polymorphic type variables when they were really just created very early
> typecheck: Modifying name of user-created type variables

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_subscript.py
Prompted by crash when student code attempted:
```
for x in list[2:]:
...
```
Resulted in a crash on line 547 because `node.slice`  was an instance of `Slice` and not `Index`, and thus did not have a `value` attribute
> typecheck: Checking that generic subscript value is index and not slice

- python_ta/typecheck/base.py
- tests/test_type_inference/test_classdef.py
This ensures that `literal_substitute` returns a copy of the original Callable when no substitutions are made.
> typecheck: Fix literal_substitute returning reference to original Callable

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_annassign.py
- tests/test_type_inference/test_function_annotation.py
- tests/test_type_inference/test_typefail_reason.py
Creating TypeFailAnnotationInvalid for invalid annotations that are not types.
Renaming TypeFailAnnotation to TypeFailAnnotationUnify to avoid confusion between two annotation type fails.
Modifying `_ann_node_to_type` to check if annotation is type or valid forward reference.
Modifying `visit_annassign` and `visit_arguments` to set `inf_type` as TypeFail if one occurs
Adding tests cases with invalid type annotations.
> typecheck: Creating TypeFailAnnotationInvalid for annotations that are not types

- tests/test_type_inference/test_lambda.py
Previous version of lambda test was specific to type variables that followed the `~_T` naming convention, however this was changed with #521
> typecheck: Generalizing str-based test in test_lambda

- python_ta/transforms/type_inference_visitor.py
There is a checker that handles this case already, but our code was previously crashing due to an index error.
> typecheck: Fix crash when an __init__ is declared without arguments

- python_ta/transforms/type_inference_visitor.py
Resolving type variables in `_lookup_attribute_type`, `visit_attribute` and `visit_subscript` before they are passed to helper functions `_gorg` and `get_attribute_class` which require concrete variables
> typecheck: Resolving type variables

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_attribute.py
This change allows us to handle attribute access of function arguments (which are unresolved classes or class instances). This is done by making an entry in `TypeStore` for the `TypeVar` corresponding to the argument and storing the attribute types within.
>  typecheck: Implement attribute inference for unresolved class names

- python_ta/typecheck/base.py
- tests/test_type_inference/test_assign_tuple.py
Prevents unification of type variable with empty tuple. Prompted by crashes when type variable is resolved as an empty tuple, which is then passed to a function that expects a type.
Still allows type variables to be unified with _type of_ empty tuple, ie. `Tuple[()]`
> typecheck: Adding support for unifying empty tuple with tuple of variables

- python_ta/typecheck/base.py
- tests/test_type_inference/test_list.py
Prompted by recursion errors raised by student code when creating nested lists with append
> typecheck: Adding check for type resolving to generic containing same type

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_for.py
Prompted by crashes when students attempted similar code
Although the test cases listed below are valid python code, it may be worth raising an error that this is not good practice
> typecheck: Adding support for subscript and attribute targets in visit_for

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/type_store.py
- tests/test_type_inference/test_dict.py
Prompted by crash caused by student code where student called sorted() on a Dict object. Type signature for sorted() is Callable[[Iterable[~T]], List[~T]], and unifying Dict with Iterable caused a crash when attempting to create a Dict object with just one argument
> Implementing support for unifying Iterable with subclasses of Iterable

- python_ta/transforms/setendings.py
Prompted by crashes when running python_ta on a blank file. `node.statement()` would simply return `node`, which also did not have attributes set
> setendings: Sets col_offset and fromlineno attributes for nodes without valid enclosing statements

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_dict.py
Examples: List becomes List[Any], Dict becomes Dict[Any, Any],
and Iterable becomes Iterable[Any].
Closes #542. (@justinpark715 I realized this is a more general approach than the one you suggested there.)
> Parse generic type annotations with no arguments.

- tests/test_type_inference/test_subscript.py
Test case now fails due to `_handle_call` returning a `TypeFail` instance with a message set by `error_func`, instead of `TypeFailFunction`
Also, unsure what this test case is actually testing? `List` is a generic type
> typecheck: Updating failing test in test_subscript

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/errors.py
Prompted by crashes when calling `subscript_error_message` while the subscript value `inf_type` is TypeVar or type(None)
> typecheck: Resolving type in error functions and checking for subscripts of type None

- python_ta/typecheck/errors.py
Prompted by error caused by:
- Variable is annotated as `list` (not `List`)
- Elements of the variable are accessed
- `subscript_error_message`  is called
- `inf_type` of the subscript value is  found to be `list` (as opposed to `List`)
- Calling `_gorg()` on `list` raises an error
> typecheck: Checking that subscript_concrete_type is a Generic

- python_ta/typecheck/base.py
Prompted by crash later in `is_descendant` because `NoneType` does not have `__name__` attribute
> typecheck: Adding check for NoneType before calling is_descendant

- python_ta/typecheck/base.py
- tests/test_type_inference/test_annassign.py
- tests/test_type_inference/test_function_def_inference.py
Prompted by errors in student code where variables were annotated with class type instead of the generic representation (ie, `list` instead of `List[Any]`), resulting in later errors when the variable is treated as a List
> typecheck: Adding helper function to better handle annotations of collection types

- python_ta/typecheck/base.py
- tests/test_type_inference/test_annassign.py
Moving check for generic annotations without proper subscripts into helper functions, so that it can be called recursively
Prompted by crash caused when student annotated something as `Union[list, int]`
(`list` is currently not properly interpreted as `List[Any]`, this should be fixed by #548 )
> typecheck: Recursively check for generic annotations without arguments

- python_ta/transforms/setendings.py
- tests/test_setendings.py
Addressed these two things
- if the parent is a `FunctionDef`, the Arguments node spans from the open parenthesis to the closing parenthesis, but not including either.
- if the parent is a `Lambda`, just set it to be the location of the colon after the `lambda` keyword
> Fix for empty Arguments node case

- nodes/DictUnpack.py
- nodes/FormattedValue.py
- nodes/JoinedStr.py
- sample_usage/TODO.md
Added astroid node documentation for the missing nodes: `FormattedValue`, `JoinedStr`, `DictUnpack`. However I did not add documentation for the following nodes: `Print`, `Exec`, `Repr`, and `EmptyNode`.
`Print`, `Exec`, and `Repr` correspond to the Python 2 statements `print`, `exec`, `(backticks as an alias for the repr() function)` which are deprecated in Python 3. Support for Python 2 will only extend till 2020 and so having documentation for it would redundant. 
`EmptyNode` has no example or explicit use even in the astroid documentation thus I chose to omit it. 
Examples for the `FormattedValue` and `JoinedStr` classes work when printed out using the `print_nodes` function, however `DictUnpack` does not and it has been outlined in the Todo file.
> Missing nodes documentation

- python_ta/checkers/constant_test_checker.py
`if 10 > 3 > 5`.
In the above code, PyTA doesn't report `10 > 3 > 5` as a style/convention error. It is an error because it will always evaluate to True/False regardless of the program state thus potentially causing one or more blocks in the if construct to always be unreachable.
> Added Check For Compare Node

- python_ta/cfg/graph.py
A minor change that makes `self.statements[-1]` a property (make it read-only by not having a setter/delete method) https://github.com/pyta-uoft/pyta/pull/582#discussion_r291438637.
> Create getter for jump

- python_ta/cfg/visitor.py
- sample_usage/draw_cfg.py
- tests/test_cfg/test_functions.py
- tests/test_cfg/test_if.py
- tests/test_cfg/test_while.py
Note: This visitor does not handle function calls only function definitions. 
Functions (or Methods) by themselves are essentially mini-programs, and because of that, I decided to create a control flow graph for each individual function (or method). Conventionally, a control flow graph is built from the `main` function of the program which results in a huge control flow graph that encapsulates all the functions used in the program. I have opted against that implementation because of the following reasons:
1. A program can include code from multiple source files but `pyta` only checks individual source files. 
2. A lot of source files (based on  CSC148) primarily have class definitions that are used in other files, and as a result, don't have a `main` function.
> CFG Function Definition Visitor

- examples/redundant_assignment_example.py
- python_ta/__init__.py
- python_ta/checkers/redundant_assignment_checker.py
- tests/test_custom_checkers/test_redundant_assignment_checker.py
This checker reports an error if a `redundant` assignment statement is found in a python program.
For an assignment statement `s` of variable `v` to be `redundant`, it must satisfy the following properties:
> 1. Every path from `s` to `v`'s  first usage goes through at least one re-definition of `v`.
> 2. Removing the statement from the program does not affect the behavior of the program in any way.
An example:
```python
y = 10    # redundant assignment
y = 20
```
A more exciting example:
```python
t = 10    # redundant assignment
for t in range(1, 10):
print(t)
x = 5    # redundant assignment
else:
x = 10
```
**Note**: only `local` assignment statements are covered in this check. This is because finding statements that satisfy property (2) is hard, however, for `local` assignments, …
> Redundant Assignment Checker

- python_ta/__init__.py
Replaces that message with a message that indicated what file was linted with what config.
This new message is printed after the linting is done.
Before:
After:
> Removes duplicated messages for config file loading

- tests/test_examples.py
Parameterized the function that tests the files in pyta/examples/pylint with pytest. Each file now corresponds to a different test when running the test suite. Some files were found to fail tests, and have been added to the IGNORED_TESTS list.
> Parametrized example tests

- python_ta/reporters/plain_reporter.py
Clear existing sorted messages when calling `sort_messages` so it will not contain duplicates if called multiple times for the same reporter
> Clear sorted messages to avoid duplicates

- python_ta/contracts/__init__.py
- tests/test_contracts.py
Added some docstrings and type contracts to functions, and marked some
functions as private. Used error re-raising to hide private functions from
traceback when an assertion fails. Tweaked error messages.
> contracts: Some code cleanup.

- python_ta/contracts/__init__.py
- tests/test_class_contracts.py
Two fixes:
- Set `DEBUG_CONTRACTS` to False by default (this is what it should've been to start)
- Fix bug where representation invariants with comprehensions didn't see `self` defined.
> Contracts improvements

- python_ta/reporters/html_reporter.py
This fixes an error where student files with non-ASCII characters weren't having their pyta_report.html being generated (and seeing a runtime error).
> reporter: Allow unicode characters in HTML report.

- python_ta/contracts/__init__.py
- tests/test_contracts.py
Fixes same problem as https://github.com/pyta-uoft/pyta/pull/652/commits/835622a4732de4b7fd8f456c007d2e8e11fc819f.
> contracts: Pass function parameters as globals when evaluating preconditions

- examples/unnecessary_indexing_example.py
- python_ta/checkers/unnecessary_indexing_checker.py
The following code snippet was raising an error:
```python
def nested_comprehension(items: list) -> None:
"""Illustrate this checker in a nested comprehension."""
for i in range(len(items)):  # Error on this line (i is highlighted).
print([[items[i] for _ in range(10)] for _ in [1, 2, 3]])
```
The reason seems to be the using the astroid `lookup` method doesn't correctly handle nested comprehensions, and instead jumps from a comprehension to the module scope when searching for an assignment node.
https://github.com/PyCQA/astroid/blob/46297774d1a0e57815500a50b2323ea906bd50da/astroid/scoped_nodes.py#L204-L208
So I changed this by rolling my own primitive `_scope_lookup`.
> E9994: fix bug with checker in nested comprehensions

- python_ta/contracts/__init__.py
- tests/test_class_contracts.py
Previously we were implicitly converting a class instance into a boolean
in _check_function_contracts. This led to an infinite recursion error if
__len__ was overridden (and __bool__ was not), or if __bool__ was
overridden, because those methods would be decorated with contract
checking as well.
Fixed this by changing the implicit boolean conversion into an explicit
`instance is None` check.
> contracts: Fix bug when class overrides __len__.

- python_ta/__init__.py
Previously, when given a file that used characters a non-UTF-8 encoding, `tokenize` raised an unhandled `UnicodeDecodeError`. It looks like we can't reliably determine what encoding is used, and so the next best thing is to report a more helpful error message to help students track down exactly which characters are causing the issue. (Usually, this is very few.)
> encoding: Gracefully handle UTF-8 encoding errors

- nodes/ann_assign.py
- nodes/arguments.py
- nodes/assert.py
- nodes/assign.py
- nodes/assign_attr.py
- nodes/assign_name.py
- nodes/async_for.py
- nodes/async_function_def.py
- nodes/async_with.py
- nodes/attribute.py
- nodes/aug_assign.py
- nodes/await.py
- nodes/bin_op.py
- nodes/bool_op.py
- nodes/break.py
- nodes/call.py
- nodes/class_def.py
- nodes/compare.py
- nodes/comprehension.py
- nodes/const.py
- nodes/continue.py
- nodes/decorators.py
- nodes/del_attr.py
Updated first 1/3rd of `pyta/nodes/...` files to be more consistent and up to date with astroid documentation. 
Added undocumented attributes to the node documentations.
Changed example documentation from:
```python
"""
Example 2:
- targets  -> [DelName(x), DelAttr(Name("self"), "attr"),
Subscript(Name(y), Index(0), Del)]
"""
```
to a format like:
```python
"""
Example 2:
Delete(
targets=[
DelName(name='x'),
DelAttr(
attrname='attr',
expr=Name(name='self')),
Subscript(
ctx=<Context.Del: 3>,
value=Name(name='y'),
slice=Const(value=0))])
"""
```
Format is based off of the `repr_tree()` method of astroid nodes. 
Ensured that `Node` object references got renamed to `NodeNG` objects.
> Update node attributes and examples 1/3

- docs/checkers/index.md
- examples/pylint/C0415_import_outside_toplevel.py
Added C0415 example file in `examples/pylint`
Added C0415 in `index.md` (under the `imports` section in numeric order with the other C041X errors)
> C0415 import outside toplevel docs

- docs/checkers/index.md
- examples/pylint/R1726_simplifiable_condition.py
Added R1726 example file to `examples/pylint`
Added R1726 to `index.md` (under `Code complexity` and `Unneeded not (C0113)` because it was a complexity-related boolean error). Also specified that R1726 is only evaluated in the context of a test condition, not any boolean operation.
Added an example correcting R1727 in `index.md`
> R1726 simplifiable condition docs

- python_ta/__init__.py
It was difficult to find which dictionary stored all the valid data types for `.pylintrc`. This comment was outdated as pylint no longer has `pylint/config.py`, but rather `pylint/config/` as a directory
Updated the comment location to be where the current pylint library keeps the `VALIDATORS` dictionary: `pylint/config/option.py`.
No testing done; it's just a python comment.
> Update VALIDATORS comment directory

- python_ta/checkers/possibly_undefined_checker.py
- tests/test_custom_checkers/test_possibly_undefined_checker.py
In the previous bug fix for the possibly undefined checker, the DictComp object case was being incorrectly processed. This PR fixes it.
**Description**: DictComp object does not have  `elt` property, instead the `key` and `value` properties is used.
> Bug Fix: accessing nonexistent DictComp object attribute

- python_ta/__init__.py
- python_ta/reporters/plain_reporter.py
the `python_ta` module's `check_all` was previously raising an error when a relative path was passed into `output=`, which aligned with the given docstring. This PR aims at changing the "absolute-path-only" restriction to allow relative paths to be passed in as well.
This also plays in to #711 as it would be inconvenient to require an absolute path for just producing the HTML in the root directory but also inconvenient to preserve the current behavior of _only_ outputting to the root directory. The relative pathing helps solve both of these inconveniences. 
`PlainReporter`'s `set_output_filepath` no longer raises its previous `IOError` when an absolute path does not exist. The file check was moved to the actual file creation in `print_messages` where the error will now be …
> Let PlainReporter and its subclasses set relative paths using `set_output_filepath`

- docs/contracts/index.md
- python_ta/contracts/__init__.py
- tests/test_class_contracts.py
- tests/test_subclass_contracts.py
This PR aims at fixing the unintended behavior where calling a helper method from the `__init__` method would prematurely check class post-conditions (class type annotations and representation invariants). This is unintended behavior as a class should be allowed to initialize before having these conditions checked.
Added extra check layer between method call and post-condition check. The additional check iterates up the call-stack to see whether the `__init__` for the method's instance exists--if said `__init__` does exist then it follows that the instance is still being initialized hence the post-condition check should be skipped.
Added test suite to `tests/test_class_contracts.py` (part of PR).
Note: this PR is overly strict …
> Allowing Helper Methods to be called from __init__

- python_ta/reporters/node_printers.py
This pull request modifies the default renderer so that it no longer highlights the entire function or class when displaying the error message. 
In `render_generic()` an additional case was added for FunctionDef/ClassDef and assigns end_line, end_col accordingly so that a single line will be highlighted and display up to 2 lines above/below. 
Ran PythonTA on E0102 and E0239 code examples (messages that have a FunctionDef or ClassDef node attribute) to observe the output
> Modify default renderer for FunctionDef and ClassDef

- python_ta/reporters/html_reporter.py
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
Introducing the Table of Contents outlined in Issue #730.
This PR has very minimal changes to the current template and is aimed to lay the groundwork to create further PRs without causing unwanted merge conflicts between changes in the `<main>` and `<aside>`. 
Current ToC features:
- locks to top of screen when scrolling on the main element
- supports scrolling when the list of errors exceeds the size of the element
- maintains fixed width when resizing
- currently has full-screen height (probably a change that's up for debate or can be changed in a later PR)
Changes can be broken up largely into two parts.
1. Added an `<aside>` element which essentially entirely contains the Table of Contents.
2. Wrapped the `<header>`, `<main>`, and new `<aside>` in a div that uses a …
> Added Table of Contents to template.html

- python_ta/reporters/templates/script.js
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
Creates a cleaner, simpler, and more intuitive graphical way to show the expand and collapse feature of the sections.
Implements the dropdown arrows from issue #730 
Changed the expand/collapse buttons into chevron SVG graphic. In addition, added functionality so that the graphic would flip based off of its collapsed state. (Faces up when closed, faces down when content is shown below.)
before:
after change:
Tested by running `python_ta.check_all()` to see how the final template ends up rendering with a file.
> Add dropdown arrows

- python_ta/reporters/templates/template.html
Due to a misunderstanding with where the dropdown arrow we ended up using came from, font awesome was improperly credited for the dropdown arrows. @ckatsube made the SVG arrow currently in the reporter template.
Remove the reference to the font awesome license.
> Remove incorrect license reference

- python_ta/reporters/html_reporter.py
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
Added internal hyperlinks to table of contents to navigate through large reports more quickly. (Part of #730)
Added ids to each file's report section and to each error instance. The naming scheme for each file is just the report # and the error instance is the report # followed by the error message's id.
Wrapped file name and error name in toc with an anchor tag with its associated href.
Added `enumerate` to the Pythonic objects passed into the template as using `{%set count = 0%}` and its increment in the loop seemed excessive. 
Manually created reports with multiple files and observed hyperlink behavior.
> Added Hyperlinks to Table of Contents

- python_ta/reporters/templates/stylesheet.css
When zooming in, the leftmost column consisting of the header and table of contents takes space priority over the actual reports. Users with poor eyesight may want to zoom in, but are ultimately unable to see the reports when attempting to.
This PR makes the table of contents and header disappear after zooming in a certain amount, allowing the reports to be the main content on the screen.
(Part of #730)
Added media selector to make header and table of contents not display when the screen width goes under 38em (approx 600px on standard font size). 
Manually created reports and observed behavior when zooming (also changed browser font size).
> Make side elements disappear when zooming in 

- python_ta/reporters/templates/stylesheet.css
#738 removed the right margin on the table of contents, which did make it fit the text better however unintentionally causes the sidebar to resize when collapsing to fit the content.
Added right margin back to style sheet. Made it equal to the left margin just to preserve some consistent spacing when zooming to the point where the sections take up their full column widths.
Images shown below.
Fully expanded table of contents
Fully collapsed table of contents
Zoomed to hit maximum column width
> reintroduce non-auto right margin to stop auto-resizing when collapsing

- CHANGELOG.md
- python_ta/__init__.py
This is a release for v2.1.0. The only major change is #760, mainly to be compatible with https://github.com/MarkUsProject/markus-autotesting/pull/296/.
> Release v2.1.0

- CHANGELOG.md
- python_ta/reporters/core.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/plain_reporter.py
When PythonTA is run on a file with no errors, the HTML reporter does not display the file, which is confusing (students aren't sure whether their file was checked). This is a regression from #727.
**Description**: Update reporters so that they always register a file, even when there are no error messages for that file. Also updated the strings displayed to the user in this case, and a related string (`no_snippet`).
Verified that the HTML report now displays files with no errors. Also ran the other reporters to verify that they print out information for files with no errors.
> html-reporter: Display file even when no errors detected

- CHANGELOG.md
- python_ta/__init__.py
Pylint version 2.10 has a bug when trying to create its cache directory: https://github.com/PyCQA/pylint/issues/4900. This causes an error message to be displayed to students, which is confusing. 
**Description**: While this was fixed in Pylint version 2.11, we're currently pinned to Pylint 2.10, so I backported the fix directly into our code for now. (It will be removed at the next major release of PythonTA.)
Verified that the pylint cache directory gets created, even when its parent directory doesn't exist.
> pylint: Manually create pylint cache directory

- docs/checkers/index.md
- examples/pylint/R1733_unnecessary_dict_index_lookup.py
Adding a short example which contains the R1733 error along with supporting documentation which explains the error and also provides an example correcting R1733. The example for R1733 is present under *Code Complexity* in `index.md`, because I believe this error makes Python code less readable and thereby results in increased complexity.
**Type of change**:
- Manually verified that the R1733 error occurs in the example file documenting this error through `pylint`.
- Ran `python -m pytest tests/test_examples.py` after creating the R1733 example file, which succeeded as well.
- Verified through `pylint` that the corrected example mentioned in documentation does not include the R1733 error.
- Ran `make html` in the `docs` directory, verifying that the documentation is …
> Adding example and documentation for R1733 (Unnecessary dict index lookup)

- docs/checkers/index.md
- examples/pylint/W1310_format_string_without_interpolation.py
Adding a short example which contains the W1310 error along with supporting documentation which explains the error and contains a code sample that resolves W1310. The example can be found in the *Miscellaneous* section of `index.md`, where documentation for some other format string related pylint errors are located as well.
**Type of change**:
- Manually verified that the W1310 error occurs in the example file documenting this error through pylint.
- Ran `python -m pytest tests/test_examples.py` after creating the W1310 example file, which succeeded as well.
- Verified through pylint that the corrected example mentioned in documentation does not include the W1310 error.
- Ran `make html` in the `docs` directory, verifying that the documentation is created for W1310.
> Adding example and documentation for W1310 (Format string without interpolation)

- CHANGELOG.md
- python_ta/__main__.py
To add two command-line options, `--generate-config` which prints out the default PythonTA configuration, and `--output-format` which accepts the specific configuration for which reporter to use.
**Description**: Added two command-line interface options in the `python_ta/__main__.py` file using the Click module.
For the `--generate-config option`, I used the classic open and read function to print the `.pylintrc` file.
For the `--output-format option`, I added `config={"output-format": output_format}` argument when calling `checker()`.
The following command-line calls have been made to test the changes.
`python3 __main__.py -g`
`python3 __main__.py`
`python3 __main__.py --output-format python_ta.reporters.PlainReporter`
`python3 __main__.py …
> Add command line interfaces

- CHANGELOG.md
- examples/ending_locations/class_def.py
- examples/ending_locations/function_def.py
- python_ta/__init__.py
- python_ta/patches/__init__.py
- python_ta/patches/messages.py
- python_ta/transforms/setendings.py
- tests/test_setendings.py
This PR includes two fixes for the ending locations transformer. The first is to register the transform using a pylint plugin rather than through monkey-patching, and then to make the module's `register` function use `init_register_ending_setters` rather than `register_transforms`, as the latter was out of date. (This was causing PythonTA to have inconsistent ending location behaviour between running its checks and the ending location test cases.)
The second fix is for `ClassDef` and `FunctionDef` nodes to only override their `fromlineno` attribute if they have decorators. Previously, in the case that they didn't have decorators, their `fromlineno` was set to be the same as that of their first child, which for `ClassDef`s could be the first statement in the class definition body. …
> Ending locations fixes

- CHANGELOG.md
- python_ta/checkers/missing_space_in_doctest_checker.py
- tests/test_custom_checkers/test_missing_space_in_doctest_checker.py
This pull request has two major changes. One was a fix with a potential bug as the FunctionDef node did not have an attribute doc_node, and that was changed to just doc. Another change was that the custom checker is now able to check for a space in the doctests in class and module docstring.
This pull request was required to allow the custom checker missing_space_in_doctest to be able to work again as well as it improves it by allowing for the checker to check module and class docstrings.
**Description**:  The first change associated with the bug was simply altering the property of the node so it would actually read the docstring with the correct attribute from the specific node. The next thing that was added was the ability for the checker to check class and module docstrings, which was …
> Space doctest change

- CHANGELOG.md
- python_ta/config/messages_config.toml
The R1710 (inconsistent-return-statements) error is commonly asked about. The current message mentions "returning None", which is not actually the most common intention of the student. (Usually the error appears when there's an if statement with a return statement in the block, and without a matching else.)
**Description**: Updated the error message.
Ran PythonTA to verify that the new error message is rendered.
> r1710: Improve error message

- CHANGELOG.md
- setup.cfg
#807 added a dependency on `toml`, but this was missing from the `setup.cfg` package config. I suspect the reason we didn't catch this in testing was one of the dev dependencies has a transitive dependency on `toml`.
**Description**: Added `toml` dependency.
Manual testing.
> deps: Add missing toml dependency

- CHANGELOG.md
- docs/debug/index.md
- python_ta/debug/accumulation_table.py
Instructor feedback on the `AccumulationTable` class!
**Description**: Based on initial instructor feedback, we've changed the display of `None` from an empty cell to a cell containing the text `None`. We've also disabled tabulate's automatic number parsing to preserve trailing `.0`, e.g. so that `14.0` is displayed as `14.0` rather than `14`. 
We also updated the `AccumulationTable` documentation based on initial feedback, including fixing the example provided.
Ran test suite and built documentation.
> accumulation table: Improve formatting of None and float, and improve documentation

- .gitignore
- README.md
It is easier to manage the dependencies of python projects using a virtual environment and we should add support for it in the gitignore file. 
When installing dependencies using macOS, the command did not work on zsh and it took time to figure out the issue. I propose a new command that should work for bash, zsh, Command shell, and PowerShell. This should work for most operating systems.
- added venv to gitignore
- changed install command for different CLI
Tested the command on zsh and this [discussion](https://github.com/mu-editor/mu/issues/852) tested it for other CLIs.
> Added venv to gitignore and changed install command for different CLI

- docs/checkers/index.md
- examples/pylint/r1736_unnecessary_list_index_lookup.py
Added documentation for new Pylint checker R1736: Unnecessary list index lookup.
Added new example file (examples/pylint/r1736_unnecessary_list_index_lookup.py) and updated PyTa checker docs (docs/pylint/index.md) to include a description and correct example under the section Code complexity.
Generated updated PyTa checker docs page with the new checker.
> Added docs for R1736: Unnecessary list index lookup

- README.md
The link to the Quick Start portion of the pyTA documentation was changed and not reflected in the README. 
- changed link to https://www.cs.toronto.edu/~david/pyta/usage/quick_start.html
- clicked on the link in the updated README
> Fixed Quick Start Link in the README file

- docs/conf.py
Removed the warning: html_static_path entry ‘_static’ does not exist that appeared when trying to generate PyTA docs.
Set html_static_path = [] in conf.py
I made temporary changes to index.md and ran the command make html to ensure that the warning message didn't appear and that the changes were present in the newly generated docs.
> fixed warning caused by `make html`

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_class_contracts.py
The motivation for this pull request was to modify the error message for a violated representation invariant to include the instance attributes' current values.
In `python_ta/contracts/__init__.py`, I modified the check so that after the check returns false (invariant was violated), it would then access the current instance attributes and include those in the error message raised. I also fixed two typos in the test file. One that said "valid" when it was testing for an invalid instance and another whose docstring value for an attribute didn't match up with what was in the precondition (100 instead of 150).
Because this change only affected the error message that was produced I just modified the existing representation invariant …
> Added instance attributes to rep invariant error message 

- CHANGELOG.md
- docs/contracts/index.md
- python_ta/contracts/__init__.py
When we use PyCharm's 'Run File in Python Console', the current module is stored as `'pydev_umd'` rather than `'__main__'` in `sys.modules`. A few places in `python_ta.contracts` relies on accessing the module of a class/function to determine what's in scope for evaluating preconditions/representation invariants. `check_all_contracts()` by default relies on decorating all functions/classes in `__main__`.
**Description**: Added a workaround to use `sys.modules['pydev_umd']` instead of `sys.modules['__main__']`, which can be turned on/off using a configuration variable.
Tested manually and by running test suite.
> contracts: Make contract checking work with PyCharm 'Run File in Python Console' action

- CHANGELOG.md
- python_ta/contracts/__init__.py
**Description**: Continuation of #867 for an additional usage of `typing.get_type_hints` when checking function parameter types.
> contracts: Fix method checks with PyCharm 'Run File in Python Console' action

- CHANGELOG.md
- python_ta/checkers/shadowing_in_comprehension_checker.py
- python_ta/config/messages_config.toml
- tests/test_check.py
Improved `tests/test_check.py` to detect fatal `astroid-error`s. This investigation was a result of some reported errors when PythonTA 2.4.1 detected certain messages.
**Description**: Updated custom messages to be consistent with expected formats in Pylint 2.15. Also updated the `shadowing-in-comprehension` checker to explicitly handle non-standard target types.
Ran test suite and manually ran PYthonTA on the example inputs for the changed messages.
> Fix custom message formats and shadowing-in-comprehension bug

- CHANGELOG.md
- python_ta/__init__.py
Calls to `check_all` and `check_errors` generate an error report when we pass in a path that doesn't exist or is unreadable. 
- PythonTA no longer opens a webpage under these conditions but still prints the error message to the console.
- Added some logic to ensure at least one file has been checked before generating reports.
- Updated `CHANGELOG.md` to document this bug fix.
- Ran the tests in the test suite and verified they passed.
- Ran `python` in `pyta` repository and called `check_all` and `check_errors` (in reality, they both use the same helper method) with erroneous inputs (both files and directories) and verified that an error message was displayed but no webpage opened. Also tested with different PythonTA reporters. …
> Fixed bug where webpage opens on bad paths

- CHANGELOG.md
- python_ta/checkers/possibly_undefined_checker.py
The `possibly_undefined_checker` was flagging comprehension variables as being possibly undefined when it shadows another variable later on in the program.
- Updated the `get_nodes` helper method in `possibly_undefined_checker.py` to fix the order of nodes being checked in the checker.
- Updated `CHANGELOG.md` to include this bug fix.
- Added the previously buggy code snippet as a test case.
- Ran the test suite and verified all tests passed.
- Ran `pyta` on the buggy code and verified that the variables are no longer flagged as being possibly undefined.
- Turns out `get_nodes` never actually checked the generator expression in the given buggy code snippet. The entire print call was treated as one `Expr` node so when it was …
> Fixed bug where comprehension variable was falsely flagged as being undefined

- CHANGELOG.md
- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_jump.py
- tests/test_custom_checkers/test_possibly_undefined_checker.py
These changes aim to fix the bug introduced in this issue's [comment](https://github.com/pyta-uoft/pyta/issues/882#issuecomment-1476670044). In addition, the current CFG implementation does not seem to handle `raise` statements (which should be similar to `return` statements) so these changes also fix this gap in the implementation.
- `raise` statements are now being handled as if they were jumps (because they are very similar to a `return` statement).
- Added the [bug](https://github.com/pyta-uoft/pyta/issues/882#issuecomment-1476670044) as a test case.
- Added a new test case to ensure that `raise` statements are correctly being handled as a jump.
- Ran the test suite and verified that they all passed.
- Added the bug as a …
> Fixed bug related to missing raise handling in CFG implementation

- docs/checkers/index.md
- examples/pylint/e1144_invalid_slice_step.py
Since Invalid Splice Step (E1144) is a new Pylint checker that was recently released and incorporated into PythonTA, this pull request was required to keep the PythonTA docs and examples up to date.
The changes made in this pull request include adding documentation for checker Invalid Splice Step (E1144) and adding an example of python code that will trigger this error.
I ran the example through Pylint and verified that the correct error was being raised. I also proofread my changes to the docs to check for grammatical errors.
> Added documentation and example for E1144 Invalid Splice Step

- docs/checkers/index.md
- examples/pylint/w3301_nested_min_max.py
The `nested-min-max` error is not documented in the pyta docs nor does it have an example showing what may cause this error. This PR aims to fix that.
- Created an example that causes the `nested-min-max` error
- Updated the `docs/checkers/index.md` file to document this error
- Ran python_ta on the example file to ensure that the intended error was being reported
- Ran python_ta on the corrected version of the example to ensure that it fixes the error
- Generated the docs to verify that the documentation was properly updated
> Added example and documentation for W3301 nested-min-max

- docs/checkers/index.md
- examples/pylint/w0644_unbalanced_dict_unpacking.py
The `unbalanced-dict-unpacking` error is not documented in the pyta docs nor does it have an example showing what may cause this error. This PR serves to fix both these problems.
- Created an example that causes the `unbalanced-dict-unpacking` error
- Updated the `docs/checkers/index.md` file to document this error
- Ran python_ta on the example file to ensure that the intended error was being reported
- Ran python_ta on the corrected version of the example to ensure that it fixes the error
- Generated the docs to verify that the documentation was properly updated
- ~~I was looking online and there doesn't seem to be much on dictionary unpacking so I'm unsure if the example provided for the "assignment" source of the error is …
> Added example and documentation for W0644 unbalanced-dict-unpacking

- docs/checkers/index.md
- examples/pylint/w3601_bad_chained_comparison.py
The `bad-chained-comparison` error is not documented in the pyta docs nor does it have an example showing what may cause this error. This PR aims to fix both of these things.
- Created an example that causes the `bad-chained-comparison` error
- Updated the `docs/checkers/index.md` file to document this error
- Ran python_ta on the example file to ensure that the intended error was being reported
- Ran python_ta on the corrected version of the example to ensure that it fixes the error
- Generated the docs to verify that the documentation was properly updated
> Added example and documentation for W3601 bad-chained-comparison

- CHANGELOG.md
- python_ta/checkers/global_variables_checker.py
- tests/test_custom_checkers/test_global_variables_checker.py
This pull request extends the GlobalVariablesChecker functionality to allow not just assignment to "constant" variables like MY_CONST, but also to type aliases like MyType = list[int].
**Description**: In the global_variables_checker.py file, added extra import statements to access the default pattern for the naming convention of type aliases as well as a pylint function to determine if a name is a python built-in name, and modified the _get_child_disallowed_global_var_nodes function to ignore type alias Name and AssignName nodes.
-Ran PythonTA on sample lines of code, which were global variable assignment statements.
-Added test cases to check that GlobalVariablesChecker detects valid and invalid type alias assignments.
> Modified GlobalVariablesChecker to allow for type alias assignment

- CHANGELOG.md
- python_ta/reporters/core.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/node_printers.py
- tests/test_messages_config/test.pylintrc
This pull request solves two problems. The first problem was that error C0303 trailing-whitespaces wasn't appearing in the HTML report. The second was that after getting the trailing whitespaces to display, the entire erroneous line of code was highlighted, rather than the trailing whitespaces.
**Description**: Modified test.pylintrc to allow error C0303 trailing-whitespaces to appear in the HTML report. Wrote a custom rendering function to allow only for trailing whitespaces to be highlighted, rather than the entire erroneous line of code. Modified html_reporter.py and core.py to make sure the line of code is not stripped of trailing whitespaces and to ensure the correct placement of highlighting on the line of code.
I have ran my code through …
> Improved message display for C0303 trailing-whitespace

- CHANGELOG.md
- python_ta/__main__.py
This pull request fixed issue #917, where running `python3 -m python_ta --generate-config` yields a `FileNotFoundError`.
**Description**: The location of `.pylintrc` has changed from `python_ta/.pylintrc` to `python_ta/config/.pylintrc`, and this was not reflected in the `main` function in `python_ta/__main__.py`. Thus, I changed the file location from "`.pylintrc`" to "`config/.pylintrc`".
Checked in the Terminal and verified that a `FileNotFoundError` was not raised and the contents of the `.pylintrc` file was displayed instead.
Did some research into the test (3.10), and apparently error 429 is that the pull request has tried to access the PyTA project too many times. However, I don't believe that I have accessed the project since the …
> Fixed issue #917

- CHANGELOG.md
- python_ta/reporters/node_printers.py
In the PEP8 error check for the number of blank lines in between functions, the highlighted line is the line that the second function starts on, rather than the blank lines that precede it, which can be misleading. This pull request solves this problem by creating a new custom renderer that will highlight the blank lines in between functions to make it clear what the error is referring to.
**Description**: Created a new custom renderer that will highlight the blank lines in between functions to make it clear what the error is referring to.
I have ran my code through PythonTA to ensure the HTML Report produces the desired outcome.
I know that the specific PEP8 error checker for this situation is E302, but I believe that there is only one single …
> Highlighted blank lines in between functions for the message display of E9989 pep8-errors

- CHANGELOG.md
- python_ta/__init__.py
- python_ta/reporters/core.py
- tests/test_config/file_fixtures/test_f0011.pylintrc
- tests/test_config/file_fixtures/test_with_errors.pylintrc
- tests/test_config/test_config.py
From #920, it is apparent that pylint does not accurately display the lines containing the error for config file parsing errors. This PR aims to prevent the reporter from displaying the incorrect lines as the source of the error and simply show no code instead.
- Added certain config file parsing error ids to `NO_SNIPPET` which prevents the reporter from displaying incorrect lines as the sources of error.
- Generalized some test cases to include the newly blacklisted config file parsing errors.
- Added a new test case to verify that no snippet was built for the blacklisted config file parsing errors.
- Updated `_override_config` to add E0015 to the reporter instead of printing to `stderr`.
- Ran the test suite and verified they …
> Removed code snippet in the error message for config file parsing errors

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts_attr_value_restoration.py
For the `new_setattr` function in `python_ta/contracts/__init__.py`, this pull request re-organizes certain variable definitions, changes the use of certain `inspect` functions, and fixes a bug with attribute value restoration when representation invariants are violated.
- Moved any variables that depend only on `klass`, but not `self/name/value`, to be defined in the outer function rather than inside `new_setattr`.
- Replaced `inspect.getouterframes` with the `f_back` to improve efficiency of code.
- The attribute value is restored to the original value if the `_check_invariants` call raises an error. 
- Used an example in another file to ensure that `f_back` represents the frame that's currently being checked in the code.
- …
> Improved the behavior of the contract checking new_setattr function

- CHANGELOG.md
- python_ta/reporters/core.py
An earlier change accidentally introduced extra newline characters in the reporter `source_lines`, which caused the code snippets to be displayed as "double-spaced" rather than the previous single spacing.
**Description**: Removed the extra new lines.
Tested manually both the PlainReporter and ColorReporter. The HTML reporter was unaffected because the newline characters weren't rendered in HTML.
> Fix double-spacing in PlainReporter and ColorReporter code snippets

- CHANGELOG.md
- python_ta/checkers/invalid_name_checker.py
- tests/test_custom_checkers/test_invalid_name_checker.py
The new `invalid-name-checker` had two bugs: it didn't allow `_` as a variable name (indicating unused names) and used the wrong check for top-level constants that were assigned to objects that were not `Const` nodes (e.g., lists).
This PR fixes #955.
**Description**: Fixed both of the above issues.
Added additional test cases and tested manually with various files.
> Fix invalid-name-checker for '_' and non-astroid.Const constants

- python_ta/checkers/forbidden_import_checker.py
- python_ta/checkers/forbidden_io_function_checker.py
- python_ta/checkers/global_variables_checker.py
- python_ta/checkers/invalid_for_target_checker.py
- python_ta/checkers/invalid_name_checker.py
- python_ta/checkers/invalid_range_index_checker.py
- python_ta/checkers/missing_space_in_doctest_checker.py
- python_ta/checkers/one_iteration_checker.py
- python_ta/checkers/possibly_undefined_checker.py
- python_ta/checkers/pycodestyle_checker.py
- python_ta/checkers/redundant_assignment_checker.py
- python_ta/checkers/shadowing_in_comprehension_checker.py
- python_ta/checkers/top_level_code_checker.py
- python_ta/checkers/type_annotation_checker.py
- python_ta/checkers/type_inference_checker.py
- python_ta/checkers/unnecessary_indexing_checker.py
The functions in the custom checkers files do not have type annotations which can make it difficult to understand the purpose of the function's parameters and what theur 
Added type annotations for all of the parameters for the functions in the files under the 'checkers' folder.
I ensured the code still functioned after making my changes by calling python_ta.check_all locally using the checkers that had the type annotations added.
> add type annotations for checkers files

- README.md
- python_ta/__init__.py
- python_ta/config/__init__.py
In the `python_ta/__init__.py` file, we currently have functions that handle configuration-related tasks. However, we also have a dedicated `config` file within the `python_ta` directory, specifically designed for managing configuration-related features in PythonTA. It would be beneficial to organize our code in a more structured manner by placing a `__init__.py` file under the proper submodule (`python_ta.config`). This `__init__.py` file would encapsulate all configuration-related functions for PythonTA, enhancing code organization and clarity.
Firstly, I created a new `.py` file under the submodule `python_ta.config` named `__init__.py`. Subsequently, I transferred all configuration-related functions, **along with the required import statements**, from …
> seperate __init__.py for handling config related functions

- CHANGELOG.md
- python_ta/config/.pylintrc
Looks like #938 accidentally introduced a bug in re-enabling pycodestyle's W503 error (due to a misconfiguration in the default `.pylintrc` file).
**Description**: Fixed the .pylintrc file.
Manual testing to verify that this check is now disabled by default.
> Ensure pycodestyle W503 is disabled by default

- CHANGELOG.md
- README.md
- python_ta/contracts/__init__.py
Addresses #961 
- I added `Class = TypeVar("Class", bound=type)` as a wildcard to match classes
- I created 2 overload methods for `check_contracts` that better reflects how the function works
I tested the following code and PyCharm doesn't show `Cannot find reference '__init__' in '(...)->Any'`
```python
from python_ta.contracts import check_contracts
@check_contracts
class Foo:
def __init__(self):
self.a = 5
@check_contracts
class Bar(Foo):
def __init__(self):
Foo.__init__(self)
```
> Fix `check_contracts` typings

- CHANGELOG.md
- python_ta/checkers/invalid_range_index_checker.py
- tests/test_custom_checkers/test_invalid_range_index_checker.py
The existing `InvalidRangeIndexChecker` uses `ast.literal_eval`, which does not work on variables, and so caused an error to be raised.
**Description**: Switch to using `astroid`'s `safe_infer` function.
Manual testing and added test cases.
> Fix invalid-range-index checker when using variables

- CHANGELOG.md
- docs/debug/index.md
- python_ta/debug/accumulation_table.py
- tests/test_debug/test_accumulation_table.py
Currently, valid accumulators for Accumulation Tables are limited to variables. Accumulators that are part of an object, such as `self.sum_so_far`, cannot be used. This limitation has been removed so users now have more flexibility when choosing their accumulation variables. 
This pull request fixes [limitation 2](https://www.cs.toronto.edu/~david/pyta/debug/) for AccumulationTable.
I modified `accumulation_table.py` so that the accumulator string passed in by the user is evaluated using the eval function if it is not found as a variable. If the variable cannot be found then a NameError will be raised.
I made sure all the existing AccumulationTable tests worked with the new feature. I also added 3 new tests, 1 with the …
> fix limitation 2 for accumulation table and add tests

- pyproject.toml
The latest version of z3 required `importlib_resources`, which does not come packaged by default in Python 3.8 or lower.
**Description**: Added this dependency for Python <3.9.
Ensure the CI tests pass on Python 3.8
> Add importlib_reload to z3 on Python < 3.9

- CHANGELOG.md
- python_ta/checkers/invalid_name_checker.py
- tests/test_custom_checkers/test_invalid_name_checker.py
The `naming-convention-violation` error was being flagged for variables defined within a main block. However, this was unintentional (and inconsistent with the global variables checker), as instructors sometimes like to use the main block to write demo code to provide to students.
**Description**: Update the `naming-convention-violation` check to exclude variables in the main block.
Tested manually and added an additional test case.
> Ensure naming-convention-violation does not check variables in main block

- CHANGELOG.md
- python_ta/checkers/invalid_range_index_checker.py
- tests/test_custom_checkers/test_invalid_range_index_checker.py
Currently, this code is being flagged as an `invalid-range-index` error:
```python
def f(numbers):
result = []
for _ in numbers:
result.append(1)
range(len(result))
```
The variable `result` was being inferred only as an empty list, which is incorrect.
**Description**: As this is an issue with astroid inference, I've modified the checker to skip all range expressions that use variables.
Added test cases and tested manually.
> Do not infer variables in invalid-range-index check

- README.md
- docs/checkers/index.md
- examples/pylint/w0134_return_in_finally.py
W0134 return-in-finally is a new check in Pylint which was added at the end of last semester, so it needed to be added to the PythonTA documentation. This pull request resolves the issue by providing documentation and examples for this checker.
Fixes pyta-uoft/pyta#999.
- Added documentation for W0134 return-in-finally checker.
- Wrote a code example that raises the W0134 return-in-finally error.
- Provided a correction to the example code that demonstrates how to resolve the W0134 return-in-finally error.
This pull request was tested using PythonTA with the code below. 
```python
import python_ta
python_ta.check_all()
```
The PythonTA report correctly showed that the W0134 (return-in-finally) error was raised.
I am not too sure …
> Added documentation and code examples for W0134 return-in-finally checker

- CHANGELOG.md
- python_ta/checkers/forbidden_import_checker.py
- tests/test_custom_checkers/test_forbidden_import_checker.py
Currently ForbiddenImportChecker only allows the specification of modules to be allowed. There are cases when the user wants specific names (like functions or variables) from modules to be allowed but not the entire module. This pull request allows the user to allow specific names (e.g., math.floor) from modules to be imported in the existing two options, `allowed-import-modules` and `extra-imports`.
Changed logic in ForbiddenImportChecker to allow for specific names to be imported in existing functions by specifying the full path, e.g. math.floor.  Also added a static helper function to convert the names from the ImportFrom nodes to be in the same format as the options. Changed the logic in the ImportFrom node handling to show a message only if the namebeing imported is not in the …
> Allowed importing specific names for ForbiddenImportChecker 

- CHANGELOG.md
- python_ta/config/messages_config.toml
One of the changes made in https://github.com/pyta-uoft/pyta/pull/1010 was to remove the line number argument from the message and replace it with the modules imported. This seemingly caused an interaction with the error message C0410 which used the line number in its message and now receives the modules imported. This change replaces the error message to better accommodate the input string given to it.
Changed the error message of C0410 in `messages_config.toml` to better fit the names of modules given to it
Changed file and then triggered message to see if updated version appeared in PythonTA window and confirmed it appeared.
> Fix C0410 error message

- CHANGELOG.md
- python_ta/__init__.py
An instructor reported that running doctest and then PythonTA on a file caused `_` to be flagged as a redefined builtin (W0622, from pylint).
**Description**: There was originally code in PythonTA that intended to remove `_` from `builtins`. However, other pylint-related imports were storing the `builtins` dict before the code was triggered. The solution was to ensure this code was executed before any other import.
Ran PythonTA after doctest, and ensured that `_` was not reported as a redefined builtin name.
> Ensure _ is removed from builtins when python_ta is imported

- CHANGELOG.md
- python_ta/checkers/top_level_code_checker.py
- tests/test_custom_checkers/test_top_level_code_checker.py
This pull request aims to resolve #1012 
Although uncommon, Python allows for type annotation to variable assignments. However, performing annotated constant variable assignment is in a different node type than regular constant assignment and causes the checker `top_level_code_checker` to incorrectly parse the statement. This causes it to consider the statement as forbidden top level code since it was uncounted for and incorrectly adds an error message. This pull request fixes the issue by parsing both annotated and unannotated constant variable assignment statements. 
Additionally, changing the attributes of classes in top level code was not picked up by the checker. This corrects the behaviour.
Changed the `_is_allowed_assignment` function in `top_level_code_checker` to parse nodes of …
> allowed annotated constants to be permitted as top level code

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts/nested_preconditions_example.py
- tests/test_contracts/test_class_contracts.py
- tests/test_contracts/test_contracts.py
- tests/test_contracts/test_nested_preconditions_example.py
When the preconditions for a function contain a call to another function whose preconditions are violated, `check_contracts` fails silently, without raising an `AssertionError`, as it happens when the violated precondition is checked direclty instead. This pull request addresses this behavior, so that nested precondition violations are correctly signaled through an `AssertionError`. In addition, this pull request also solves a related issues with Representation Invariants, allowing for the use or user defined functions (possibly with preconditions) within representation invariants.
closes #1003 
I modified part of the exception handling in `python_ta.contracts.__init__.py`. The functions `_check_assertions` and `_check_invariants` now raise an `AssertionError` directly when an …
> Raise AssertionError when precondition contains precondition violations

- CHANGELOG.md
- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_label_if.py
- tests/test_cfg/test_label_while.py
Currently the edges in a generated control flow graph coming out of If and While conditions are labelled with True or False. We can augment the edge instead to store the actual condition as an attribute, allowing us to accumulate logical conditions along a particular path in the graph.
Added a new instance attribute to CFGEdge called condition to represent the condition node. Updated methods that add an label to also add a condition.
Added automated tests to see if condition attributes were set correctly. The attributes are not visibly displayed in the generated CFG.
> added CFGEdge augment to store condition node in If/While conditions

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts/test_class_contracts.py
When a representation invariant of a class invokes one of its methods, the representation invariants for that class keep being checked recursively, leading to infinite recursion. This pull request fixes this issue, allowing to use class methods in representation invariants for more flexibility.
I temporarily added an attribute `__pyta_currently_checking` to the instance whose representation invariants are being checked. Such attribute is added at the beginning of the check and deleted at the end, and the representation invariants are only checked when this attribute exists. Finally, I modified `new_setattr` to skip the representation invariant check exclusively for the `__pyta_currently_checking` attribute.
I added four tests to …
> Fixed infinite recursion in representation invariants with method calls

- CHANGELOG.md
- python_ta/transforms/ExprWrapper.py
- tests/test_z3_visitor.py
Extend `ExprWrapper` to support `List/Set/Tuple` literals and `in/not in` operators.
...
<details>
</details>
| ♻️ …
> feat: add support for container literals and in operator in ExprWrapper

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/test_snapshot.py
Updated `snapshot.py` and `test_snapshot.py` to align with changes to JSON in MemoryViz 0.2.0. 
Primary changes were:
- Replacing "name" with "type' when in reference to type of an object
- Using the ".class" and ".frame" types to replace usage of isClass and stack-frame.
| 🐛 _Bug fix_ …
> Updated snapshot.py to align with MemoryViz 0.2.0 changes

- CHANGELOG.md
- python_ta/checkers/invalid_name_checker.py
Fixed all but 3 of the previous 1769 warnings raised when running `pytest tests`.
<details>
Before:
After:
</details>
| …
> Fix Pytest Warnings

- CHANGELOG.md
- python_ta/transforms/z3_visitor.py
Change the use of `inferred()` to `astroid.util.safe_infer()` to prevent `InferenceError` for uninferable types
Add handling of `AstroidError` in parsing python expressions to Z3 expressions via `ExprWrapper`
...
<details>
</details>
| ✨ _New feature_ (non-breaking change that adds functionality)                          | …
> refactor: Change `inferred` to `safe_infer` and Add Handling for `AstroidError` in `Z3Visitor`

- CHANGELOG.md
- python_ta/transforms/ExprWrapper.py
- tests/test_z3_visitor.py
Support `!=` in `apply_bin_op()`
Use `get()` in dictionary lookup in `apply_name()` to prevent `KeyError`
...
<details>
</details>
| 🐛 _Bug fix_ (non-breaking change that fixes an issue)                                  | …
> feat: Support `!=` Operator in ExprWrapper

- CHANGELOG.md
- pyproject.toml
- python_ta/__init__.py
- python_ta/cfg/graph.py
- python_ta/transforms/__init__.py
- tests/test_transforms/test_expr_wrapper.py
Release for v2.8.1. I had to made a quick fix release after making v2.8.0 as I found that v2.8.0 incorrectly relied on `z3-solver` being installed.
> Release v2.8.1!

- CHANGELOG.md
- tests/test_debug/test_snapshot.py
The `test_snapshot_to_json_sets_primitive` was failing exclusively in Python 3.8 due to the non-deterministic iteration order of Python sets. Since sets do not guarantee a particular order, the test would fail under certain conditions when the order was inconsistent.
To resolve this issue, I modified the test to focus on verifying the `type` and `value` fields of the JSON objects, while ignoring the `id` field. This removes any dependency on the iteration order and ensures the test passes reliably across different Python versions.
...
| …
> Modified test_snapshot_to_json_sets_primitive for 3.8

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/test_snapshot.py
Add a `exclude_vars` parameter to `snapshot` to allow filtering variables.
...
<details>
</details>
| ✨ _New feature_ (non-breaking change that adds functionality)                          |    x      |
| ♻️ _Refactoring_ …
> Add variable fitler to snapshot

- CHANGELOG.md
- python_ta/cfg/graph.py
- python_ta/checkers/one_iteration_checker.py
- tests/test_cfg/test_edge_feasibility.py
- tests/test_cfg/test_z3_constraints.py
- tests/test_custom_checkers/test_one_iteration_checker.py
- Resolved an issue where CFG edges from the loop body to the loop condition block were ignored during the augmentation of Z3 constraints.
- Fixed incorrect reporting of messages for while loops in the one-iteration-checker when the z3 option is enabled.
...
<details>
</details>
_(Write an `X` or a brief description next to …
> Fix Loop Handling and Reporting Issues in Z3 Constraints and `one-iteration-checker`

- CHANGELOG.md
- python_ta/patches/transforms.py
This pull request fixes #1117 and adds logging for when `Z3Visitor` and `CFGVisitor` fail to run. In particular, this will report a warning if the `z3` option is enabled, but `z3-solver` was not installed.
<details>
</details>
| …
> Fix crash when z3 is missing and add transform error reporting

- CHANGELOG.md
- examples/custom_checkers/e9989_pycodestyle/e262_error.py
- python_ta/reporters/node_printers.py
- tests/test_custom_checkers/test_pycodestyle_checker.py
The current implementation of `render_pep8_errors_e262` raised an error when an inline comment had a `#` that was not followed by any spaces. This PR fixes that bug.
<details>
</details>
| Type …
> Fixed crash when an inline comment had no spaces after the #

- CHANGELOG.md
- python_ta/__init__.py
- tests/test_black.py
This PR fixes a bug when `python_ta.check_all` is called with `autoformat=True`, and no `max-line-length` configuration value is provided. In this case a line length of 88 was used, instead of the correct value of the linter configuration option.
<details>
</details>
_(Write an `X` or a brief description next to the type or …
> Ensure max-line-length default value is used when autoformat=True

- CHANGELOG.md
- python_ta/debug/accumulation_table.py
- tests/test_debug/test_accumulation_table.py
Previously, if `AccumulationTable` was passed an accumulation expression that involved a loop variable, evaluating that expression for the first row of the table (representing state before the loop executes) led to a `NameError` because the loop variable was not yet defined.
This PR fixes this bug by handling this `NameError`; it relies on the `name` attribute of this error, which is …
> Allow AccumulationTable accumulation expressions to refer to loop variables

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/snapshot_main_frame.py
- tests/test_debug/test_snapshot.py
This pull request fixes two issues related to the `python_ta.debug.snapsnot`'s `snapshot` function.
1. Some imported objects (including `from __future__ import annotations`) were not being filtered out in the `get_filtered_global_variables` helper, leading them to appear in the returned snapshot object. I've strengthened this filter by using `inspect.getmodule(obj)` to determine the …
> Improvements to python_ta.debug.snapshot

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts/test_class_contracts.py
The Representation Invariant checker timing is currently too strict. In many data structures, it's common for instances to mutate other instances of the same type (i.e. graphs/trees or recursive data structures). The current logic enforces RI checks in two places: 1) when an attribute is set EXCEPT for instance methods 2) after the instance method is called. The problem is that Path 1 is executed inside instance methods that set the attributes of different instances of the same type (motivating example below).
The proposed change is to additionally exempt instances of the same type as `self` during the Path 1 check and push checking these RIs until after the instance method has returned, alongside the Path 2 check.
<details>
<summary>More practical motivating example with …
> Relax Representation Invariant Checking Logic for Recursive Classes

- CHANGELOG.md
- python_ta/__init__.py
- python_ta/cfg/cfg_generator.py
- python_ta/check/watch.py
- python_ta/checkers/condition_logic_checker.py
- python_ta/checkers/forbidden_import_checker.py
- python_ta/checkers/global_variables_checker.py
- python_ta/checkers/invalid_name_checker.py
- python_ta/checkers/possibly_undefined_checker.py
- python_ta/checkers/pycodestyle_checker.py
- python_ta/checkers/redundant_assignment_checker.py
- python_ta/checkers/static_type_checker.py
- python_ta/checkers/unmentioned_parameter_checker.py
- python_ta/checkers/unnecessary_indexing_checker.py
- python_ta/contracts/__init__.py
- python_ta/debug/accumulation_table.py
- python_ta/debug/recursion_table.py
- python_ta/debug/snapshot.py
- python_ta/debug/snapshot_tracer.py
- python_ta/reporters/core.py
- python_ta/reporters/json_reporter.py
- python_ta/reporters/plain_reporter.py
- python_ta/util/autoformat.py
- python_ta/utils.py
- tests/test_config/test_config.py
- tests/test_init_logging.py
Completed the following two cleanup tasks:
1. Removed unused imports from python_ta/__init__.py and all files it imports.
2. Wrapped type-only imports in if TYPE_CHECKING guards to avoid unnecessary runtime imports.
...
> C Profile Overview:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
85    0.001    0.000    1.054    0.012 __init__.py:1(<module>)
712/1 …
```
> Refactor reporter loading and imports

- CHANGELOG.md
- python_ta/debug/accumulation_table.py
- tests/test_debug/test_accumulation_table.py
Fixes a bug in the `AccumulationTable` class where loop variable names weren't being captured for nested targets.
Now supports both single variables and nested unpacking like `for a, (b, c) in ....`
I used the `astroid.nodes_of_class` method and added logic to handle both flat and nested loop targets.
...
<details>
</details>
| …
> Improve Loop Variable Extraction for Nested Structures in the Accumulation Table Class

- CHANGELOG.md
- docs/debug/index.md
- python_ta/debug/accumulation_table.py
- tests/test_debug/test_accumulation_table.py
In this PR, I've added a third optional parameter to the AccumulationTable class, allowing users to specify the output format as either `"table"` or `"csv"`. Currently, the class already supported writing output to files, but only in the default 'table' format.
By integrating file output with the 'csv' format, this change makes it easier to log results in a standardized format that’s easy to parse.
Finally, I added 2 new tests to verify this functionality. I also updated the documentation accordingly.
| `output`          | `format`  | Behavior                                                                                         |
|-------------------|-----------|--------------------------------------------------------------------------------------------------|
| `None`            | …
> Added output format parameter to AccumulationTable

- tests/test_cfg/test_cfg_generator_z3.py
I wrote two versions of the same failing test. These tests provide coverage for the import error code in the `_generate` helper in `cfg_generator.py`.
Here are my two best attempts:
1) attempt 1: Use patching to "mock" the error
2) attempt 2: Use monkeypatching to manually replace the module with a "dummy" module
I also tried:
- Using patch to replace the module with a "dummy" module (instead of None)
- Using monkeypatching to manually delete the module
> Failing GitHub CI coverage tests [FOR @david-yz-liu]

- CHANGELOG.md
- python_ta/check/helpers.py
- python_ta/reporters/core.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/json_reporter.py
- tests/test_check.py
- tests/test_config/file_fixtures/test_color_no_errors.pylintrc
- tests/test_config/file_fixtures/test_color_unknown_key.pylintrc
- tests/test_config/file_fixtures/test_html_no_errors.pylintrc
- tests/test_config/file_fixtures/test_html_unknown_key.pylintrc
- tests/test_config/file_fixtures/test_json_no_errors.pylintrc
- tests/test_config/file_fixtures/test_json_unknown_key.pylintrc
- tests/test_config/file_fixtures/test_plain_no_errors.pylintrc
- tests/test_config/file_fixtures/test_plain_unknown_key.pylintrc
- tests/test_config/test_config.py
Pylint checks configuration files for errors, registering these files in the reporters. Previously, the reporters included a section for custom configuration files in the output report (invoking `print_messages/`display_messages`), which is not expected behaviour (and not the case in previous versions of PyTA).
This PR fixes this by:
- fixing the guard to `reporter.print_messages` in the …
> Fixed reports to only include config files when they have errors

- CHANGELOG.md
- python_ta/reporters/node_printers.py
Refactored node_printers.py to reduce code duplication. Created new helper function that calculates the column number of the error and made the render_context calls (the calls responsible for printing the context lines above and below the error line) from render_pep8_errors instead of calling the function inside each renderer.
...
<details>
</details>
| ✨ _New feature_ (non-breaking change that adds functionality) …
> refactoring node_printers.py
