- reporters/color_reporter.py
- reporters/plain_reporter.py
Added line numbers to the error messages. Fixes Issue #81.
> Line Numbers (Error Reporting)

- checkers/forbidden_import_checker.py
revert the coloring back to normal in the terminal.
> fixed terminal output to revert back to original color after colorama

- pyta.py
The old code caught an `AttributeError`, which was too general (hides other potential errors in one of the checkers).
> missing-module-detection: Detect missing module earlier, remove false positives

- checkers/forbidden_import_checker.py
Checks for forbidden imports in `from ___ import ____` statements.
> forbidden-import-checker: check for imports in ImportFrom nodes

- pyta.py
Created a new checker for pycodestyle. It prints out the messages from pycodestyle using its API. Address issue #90.
> Pycodestyle Checker

- python_ta/checkers/always_returning_checker.py
@Jasminewwwu should find this interesting.
> Fix always_returning_checker.py and refactor the code

- examples/pycodestyle_example.py
- python_ta/__init__.py
- python_ta/checkers/pycodestyle_checker.py
Created a separate checker for Pycodestyle (PEP8) checker using the Raw Checker. Addresses issue #90.
> Pycode checker

- python_ta/checkers/IO_Function_checker.py
- python_ta/checkers/dynamic_execution_checker.py
- python_ta/checkers/global_variables_checker.py
- python_ta/checkers/invalid_range_index_checker.py
This will resolve the (current) last to-do on issue #135, correcting a non-unique identifier problem that is inconsistent with Pylint (as well as a couple of other minor removals of redundancy). (Please check off that to-do once this is pulled.)
> Make corrections to checker options (see #135)

- nodes/Assign.py
- nodes/AsyncFor.py
- nodes/AsyncFunctionDef.py
- nodes/Attribute.py
- nodes/Call.py
- nodes/ClassDef.py
- nodes/Const.py
- nodes/TODO.md
> improvement on docs 

- nodes/AssignAttr.py
- nodes/AssignName.py
- nodes/AsyncWith.py
- nodes/Attribute.py
- nodes/DelAttr.py
- nodes/DelName.py
- nodes/Delete.py
- nodes/ListComp.py
- nodes/Name.py
- nodes/Nonlocal.py
- nodes/README.md
- nodes/Return.py
- nodes/Set.py
- nodes/Slice.py
- nodes/Starred.py
- nodes/TODO.md
- nodes/TryExcept.py
- nodes/TryFinally.py
- nodes/While.py
- nodes/With.py
- nodes/Yield.py
- nodes/YieldFrom.py
This contains my work on the suggestions listed in the TODO file in the nodes directory. I am also deleting tasks from TODO as I finish them.
So far: 
* Fixed description of `ctx` in the README, reflected that change in the relevant node docs.
* Corrected minor error in `Name` node doc.
> Node docs fixes

- nodes/Decorators.py
- nodes/DelAttr.py
- nodes/DelName.py
- nodes/Delete.py
- nodes/Dict.py
- nodes/For.py
- nodes/FunctionDef.py
- nodes/If.py
- nodes/IfExp.py
- nodes/Lambda.py
- nodes/TODO.md
Please merge this pull request after I have finished all the rest of the TODO's. I'll likely finish the rest of them during the break.
Finish the TODO's for:
> Node Documentations TODO's

- python_ta/parser/__init__.py
- python_ta/parser/test_parser.py
- setup.py
Uses funcparserlib to encode the [Python grammar](https://docs.python.org/3/reference/grammar.html), with tests from [here](https://github.com/python/cpython/blob/master/Lib/test/test_parser.py).
> Add a basic syntax checker

- nodes/TODO.md
I realised these changes have already been made, so this is just cleanup.
> Update TODO list for nodes

- tests/type_inference/test_literals.py
Added test cases for:
- String indexing
- Tuple indexing
- List indexing
- Dictionary indexing
> Index test

- python_ta/typecheck/base.py
- Implement helper methods to access and mutate private attributes.
> Environment class helpers

- python_ta/transforms/type_inference_visitor.py
- Create helper for setting local environment.
- Implement separate methods for setting environment of FunctionDef node, Module node (ClassDef node next?)
- Update register
> Reimplement set environment

- python_ta/typecheck/base.py
- Helper for implementing set_name_type_constraints
> Implement helper method to facilitate adding variables to environment.

- python_ta/transforms/type_inference_visitor.py
> Remove outdated environment setter.

- python_ta/transforms/type_inference_visitor.py
- Fix typo in function name.
- Instantiate environment attribute for FunctionDef node.
> Fix function def visitor

- python_ta/transforms/type_inference_visitor.py
- tests/type_inference/test_literals.py
- Import TYPE_CONSTRAINTS object.
- Create test case for single variable assignment.
> Test single target assign

- tests/type_inference/test_literals.py
- Add test case for set-name visitor for single unassigned variable.
- Add test case for set-name visitor using hypothesis for random number of assigned variables.
> Add test cases set name

- python_ta/transforms/type_inference_visitor.py
- tests/type_inference/test_literals.py
- Implement visitor for Name node representing multi-target-assignment statement (ie. a, b = 3, 4)
- Add test case for aforementioned statements.
> Dev test multi target assignment statement

- tests/custom_hypothesis_support.py
- tests/type_inference/test_assignments.py
- tests/type_inference/test_literals.py
- Extract test cases for assignment statements into separate file.
- Fix import statements accordingly.
- Move parsing function into helpers module.
> Refactor testing.

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/type_inference/test_functions.py
- Reimplement visitor for functionDef node type setter using helper.
- Create test module for function related programs.
- Implement test cases for simple programs containing function definitions with no parameters.
> Dev test function def

- tests/custom_hypothesis_support.py
- Add helper function to return generator for valid identifiers.
> Add helper to return valid identifiers.

- python_ta/typecheck/base.py
- Implement helper method to get types in Callable representing a function.
> Add helper for getting types from a Callable

- tests/custom_hypothesis_support.py
- Include iskeyword() check in strategy for generating valid IDs.
- Update variable, value dictionary strategy using aforementioned strategy.
> Update hypothesis helpers

- python_ta/typecheck/base.py
- Initialize list for returning in helper.
> Fix helper method for returning types contained in Callable

- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/type_inference/test_assignments.py
- tests/type_inference/test_functions.py
- Extend visitor to deal with non-returning function definitions in programs.
- Add test case to verify proper type setting of function definition.
> Dev test non returning function

- python_ta/typecheck/type_store.py
- Rename methods attribute to functions
- Import Any
- Change value of dictionaries to tuples; instantiate Callables with types not strings.
> Reimplement type store

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/type_store.py
- Rename methods attribute to functions.
- Add method lookup_functions to TypeStore class to replace lookup_methods.
- Instantiate TYPE_STORE singleton.
- Fix path setting of TypeShed source code.
> Add method type store

- nodes/BinOp.py
- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/type_inference/test_ops.py
- Add function that returns strategy for generating boolean operator symbol.
- Helper to get non-boolean primitive values.
> Add helpers.

- examples/pylint/E1111_assignment_from_no_return.py
- examples/pylint/E1128_assignment_from_none.py
> Update examples of type errors for the website

- python_ta/transforms/type_inference_visitor.py
- tests/type_inference/test_boolops.py
- Re-document BoolOp visitor.
- Implement visitor for BoolOp using Union.
- Add test case for BoolOp representing binary boolean operation.
> Dev test boolops

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/custom_hypothesis_support.py
- tests/type_inference/test_unaryops.py
- Update dunder function with unary symbols.
- Add strategy for generating unary operation.
- Add test cases for UnaryOp nodes representing unary operation.
> Dev test UnaryOp

- nodes/Compare.py
- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/custom_hypothesis_support.py
- tests/type_inference/test_compare.py
- Update dunder helper with compare operators
- Implement test case for Compare node representing comparisons between homogeneous-typed values.
- Add TODO for unification problem between a type and object type.
> Dev test compare

- nodes/For.py
- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/type_inference/test_for.py
- Implement visitor for For node.
- Add test cases to test inference of bound names in for loop statement as well as scope setting of locally bound target names.
> Dev test for

- examples/pylint/W0125_using_constant_test.py
- examples/pylint/W0612_unused_variable.py
- examples/pylint/W0613_unused_argument.py
Accompanies: pyta-uoft/website#58
> Week 4: Code complexity

- nodes/IfExp.py
- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_ifexpr.py
- Update documentation for IfExpr node.
- Implement IfExpr node visitor.
- Add test cases for IfExpr node representing an assignment of an if expression to a variable with both body/orelse suites having the same type as well as different types.
> Dev test ifexpr

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- Refactor visitors.
- Implement helper function that looks up a function, unifies the function call with given arguments 
and returns a return type wrapped in the TypeInfo wrapper.
- Write more informative TypeErrorInfo messages in helper.
- Reimplement Name, BinOp, UnaryOp, Subscript, Assign, For node visitors using helper.
> Refactor code visitor

- examples/pylint/C0103_invalid_name.py
- examples/pylint/E0102_function_redefined.py
- examples/pylint/E0401_import_error.py
- examples/pylint/W0621_redefined_outer_name.py
- examples/pylint/W0622_redefined_builtin.py
Stylistic changes to some examples.
Goes together with pyta-uoft/website#61.
> Week 7: Imports errors

- examples/pylint/W0199_assert_on_tuple.py
- examples/pylint/W0201_attribute_defined_outside_init.py
- examples/pylint/W0233_non_parent_init.py
Goes together wtih pyta-uoft/website#62.
> Week 8: Remaining sections

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_assignments.py
- Implement helper to facilitate type lookups.
- Update visitors accordingly.
> Refactor code lookups

- python_ta/typecheck/base.py
- tests/test_type_inference/test_classdef.py
- Add test case for checking types of annotated method call.
- Reimplement annotation parser to handle instance method definitions.
 
> Dev test method call annotations.

- nodes/AnnAssign.py
- python_ta/transforms/type_inference_visitor.py
- tests/custom_hypothesis_support.py
- tests/test_type_inference/test_annassign.py
- Add documentation for AnnAssign node in nodes directory.
- Implement visitor for AnnAssign node visitor.
- Implement one concrete and one hypothesis test case for AnnAssign node.
> Dev test AnnAssign

- examples/dynamic_execution_example.py
- examples/pylint/C0123_unidiomatic_typecheck.py
- examples/pylint/E1305_too_many_format_args.py
- examples/pylint/E1310_bad_str_strip_call.py
- examples/pylint/W0102_dangerous_default_value.py
- examples/pylint/W0212_protected_access.py
- examples/pylint/W1303_missing_format_argument_key.py
- examples/pylint/W1401_anomalous_backslash_in_string.py
- examples/pylint/W1503_redundant_unittest_assert.py
- examples/syntax_errors/assignment_inside_condition.py
- examples/syntax_errors/assignment_to_keyword.py
- examples/syntax_errors/assignment_to_literal.py
- examples/syntax_errors/missing_colon.py
- examples/syntax_errors/missing_parentheses_in_call_to_print.py
- examples/syntax_errors/missing_quote.py
- examples/syntax_errors/undefined_operator.py
- examples/syntax_errors/unexpected_indent.py
- examples/syntax_errors/unindent_does_not_match_indentation.py
Goes together with pyta-uoft/website#65.
Includes commits from pyta-uoft/pyta#295 and pyta-uoft/pyta#296.
> Syntax errors / Miscellaneous / Custom errors

- tests/test_type_inference/test_annassign.py
- tests/test_type_inference/test_assignments.py
- tests/test_type_inference/test_binops.py
- tests/test_type_inference/test_boolops.py
- tests/test_type_inference/test_compare.py
- tests/test_type_inference/test_dictcomp.py
- tests/test_type_inference/test_for.py
- tests/test_type_inference/test_function_def_inference.py
- tests/test_type_inference/test_functions.py
- tests/test_type_inference/test_ifexpr.py
- tests/test_type_inference/test_listcomp.py
- tests/test_type_inference/test_literals.py
- tests/test_type_inference/test_setcomp.py
- tests/test_type_inference/test_subscript.py
- tests/test_type_inference/test_unaryops.py
- Surpressed HealthChecks in all test cases that generate using hypothesis.
- Build will break due to error that is addressed in error-messages branch.
> Surpress HealthChceks in test cases.

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
- tests/test_type_inference/test_binops.py
- Get dunder form of builtin functions via dictionary access instead of using a hard-coded function.
- Update calls to deprecated function to dictionary accesses.
- Update helper.
- Fix formatting of whitespaces.
> Binary op error

- tests/test_type_constraints/test_unify.py
Adds additional tests for unify.
> Type constraints tests

- tests/test_type_inference/test_functions.py
- Add assertion to incompatible binary operation test case.
> Update test case for BinOp typechecking test case.

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_classdef.py
Fixing bug where instance attributes were not being properly added to type_store, causing problems when looked up in visit_attribute
Updating test cases
> Typecheck: visit_attribute

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_function_overload.py
Improving checking for Unions in type_inference_visitor
Separating test cases in test_function_overload that were affecting each other
> Typecheck: Function overload bug fix

- .gitignore
- python_ta/typecheck/README.md
Editing gitignore to ignore .DS_Store files
Editing readme to remove completed todos
> gitignore, readme

- tests/test_type_inference/test_tnode_structure.py
This file will contain tests analogous to the examples in the Wiki. For now, I've included only one test so that we can first agree whether this is the correct approach to writing these tests.
> typecheck: Add a test file for anticipated type inference modifications

- sample_usage/draw_tnodes.py
Also print Union types more compactly.
> typecheck: Draw TypeFails in graphs

- nodes/Call.py
Corrected documentation and added an example in Call.py.
> Call node documentation

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_classdef.py
Updating inferred type of initializer functions to be ForwardRef. Updating relevant test cases
Issue discovered while doing preliminary work in updating visit_call
> typecheck: Updating inferred type of initializer function

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- python_ta/typecheck/base.py
Updating more visit functions in type_inference_visitor to use unify with new decorator. Updating readme
> typecheck: Updating more visit functions in type_inference_visitor

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/README.md
- python_ta/typecheck/base.py
- tests/test_type_inference/test_function_def_inference.py
Updating visit_functiondef, visit_slice to use monadic functions
Adding helper functions lookup_inf_type, create_Callable_TypeResult
Updating relevant test cases
> Updating visit_functiondef, visit_slice to use monadic functions

- tests/test_type_constraints/test_tnode_structure.py
- tests/test_type_inference/test_attribute.py
Also fix incorrect test in `test_attribute`
> typecheck: Re-add skipped test in test_tnode_structure

- python_ta/transforms/type_inference_visitor.py
Adding visit function to ensure all nodes have inf_type attribute
> typecheck: Adding inf_type attribute to all nodes

- examples/type_annotation_example.py
- python_ta/__init__.py
- python_ta/checkers/type_annotation_checker.py
Adding checker for type annotations. Currently support type signatures for functions and methods, class variables, and instance variables
> typecheck: Adding type annotation checker

- python_ta/typecheck/base.py
Generalizing find_parent to a find_node function used by find_parent and find_functiondef
find_function_def to be useful for a future TypeFailFunction subclass
> typecheck: Generalizing find_parent

- python_ta/transforms/type_inference_visitor.py
While working on modifying lookup_typevar to be monadic, discovered that functions that return multiple values, such as get_attribute_class, do not work well with TypeFail. This updates the usage of get_attribute_class to account for the possibility of TypeFail
> typecheck: Fixing get_attribute_class to account for TypeFail

- python_ta/checkers/type_inference_checker.py
- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/type_store.py
- tests/test_type_inference/test_binops.py
- tests/test_type_inference/test_functions.py
Also removing obsolete TypeErrorInfo and related code
> typecheck: Adding TypeFailFunction support to _handle_call

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
Fixing crashes in nodes/Return.py
> typecheck: Adding support for invalid return nodes

- nodes/Comprehension.py
Left a note better explaining the example for the comprehension node documentation!
> updated the Comprehension Node documentation

- python_ta/transforms/type_inference_visitor.py
- python_ta/typecheck/base.py
Adding type annotations and docstrings to base.py and type_inference_visitor.py
> typecheck: Adding type annotations and docstrings

- python_ta/transforms/type_inference_visitor.py
- tests/test_type_inference/test_binops.py
I forgot to add this in my PR for `get_call_signature`.
> Use getattr in get_attribute_class

- python_ta/transforms/type_inference_visitor.py
Previous implementation would inadvertently modifying the type store at line 757 `func_type.__args__ = func_type.__args__[1:]`, causing the type signature in type store to be reduced by one parameter each time the function was called. This was noticed while testing the type inference checker on student code. 
Some test cases are failing, this is due to `create_Callable` mistakenly treating some regular type variables as polymorphic. This issue is resolved in #521 and once both pull requests are merged, all tests pass
> typecheck: Creating new callables in visit_attribute to avoid accidental modification of type store

- python_ta/patches/error_messages.py
- python_ta/reporters/node_printers.py
- setup.py
> Add custom renderer for R0913_too_many_arguments

- python_ta/cfg/__init__.py
- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- sample_usage/draw_cfg.py
- sample_usage/draw_tnodes.py
- sample_usage/print_ast.py
- setup.py
- tests/test_cfg/test_if.py
Inspired by https://github.com/coetaur0/staticfg.
> Initial work for control flow graphs

- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_while.py
Added `while` visitor method as well as the corresponding tests.
> CFG - While Node Visitor

- python_ta/cfg/graph.py
Add comment to clarify the purpose of block_count
> Add comment on block_count

- python_ta/cfg/visitor.py
- tests/test_cfg/test_for.py
Pretty much the same as the while visitor. Thanks @kavins14!
> CFG For Visitor

- python_ta/cfg/visitor.py
- tests/test_cfg/test_classdef.py
https://github.com/pyta-uoft/pyta/pull/597#discussion_r305414569
> Updated Class Def Visitor

- python_ta/reporters/templates/template.html
Made all the code snippets collapsible individually in the error report webpage for a better user experience.
> Added collapsible code snippets

- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- sample_usage/draw_cfg.py
- tests/test_cfg/test_unreachable.py
> Unreachable Block Identification

- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_tryexcept.py
Added CFG building functionality for `try/except` compound statements. 
Note that only the final block(s) of the `try` body will be linked to the `except` blocks. This is basically a subset of all the possible edges in the `try/except` CFG representation.
> Visitor: Try-Except

- python_ta/contracts/__init__.py
- tests/test_contracts.py
Fixes the ability for users to add their own functions in function contracts.
Adds test cases too
> Allows users to use their own functions in their contracts

- python_ta/contracts/__init__.py
- tests/test_class_contracts.py
This sets up the basic structure for class contracts and adds tests. A sample use case is contained in the testing file that's added.
> Adds class contracts and representation invariants

- python_ta/contracts/__init__.py
- setup.py
- tests/test_class_contracts.py
- tests/test_subclass_contracts.py
The following have been added:
- The scope in which the class is defined is now accessible while evaluating representation invariants.
- Basic support for sub classes. This will continue being tested and improved upon.
> Adds Subclasses and Class Scope

- python_ta/contracts/__init__.py
- setup.py
- tests/test_class_contracts.py
- tests/test_subclass_contracts.py
- Added more comprehensive tests
- Adds the ability to auto decorate a single module.
- Instead of classes being decorated they are now directly modified.
- classmethods and staticmethods now work.
> Redoing parts of the code

- python_ta/__init__.py
- setup.py
> Fix memory leaks

- python_ta/contracts/__init__.py
This stops PythonTA from intercepting `AssertionError`s raised by assertions written in the actual function code.
> contracts: Raise custom PyTAContractError internally instead of AssertionError

- docs/checkers/index.md
- examples/pylint/W0105_pointless_string_statement.py
Added error `W0105` Pointless string statement pylint example and documentation.
> Error pointless string statement docs

- docs/checkers/index.md
- examples/pylint/R1732_consider_using_with.py
- Created example
- Added documentation to index.md
> Error R1732 docs

- docs/checkers/index.md
-Added 'E' that was missing from the tag
> E9989 doc fix

- docs/checkers/index.md
- examples/pylint/R1725_super_with_arguments.py
Added R1725 example file in `examples/pylint`
Added R1725 in `index.md` (under the `Classes and objects` section right underneath `Bad parent init (W0233)` as the super function is introduced there
> R1725 super with args docs

- .github/PULL_REQUEST_TEMPLATE.md
I made a mistake in the merged #709 when reverting 2 of the undesired changes that left two `
N/A
> Refactor PR Template Comments Again

- python_ta/checkers/shadowing_in_comprehension_checker.py
- tests/test_custom_checkers/test_shadowing_in_comprehension_checker.py
This pull request is required to resolve an issue with the shadowing-in-comprehension checker where "_" is flagged as a shadowed variable. 
Changes include creating a test suite for this checker and adding an extra condition in the checker code to ignore "_". 
This pull request was tested by creating a test suite for the checker using the examples from the example file and testing it with examples using "_".
> E9988 Bug Fix 

- python_ta/contracts/__init__.py
- tests/test_contracts.py
This PR aims at adding a section in the `python_ta/contracts` for additional helpful suggestions to appear during specific circumstances. The added section is specifically for the function argument type annotation preconditions.
The added suggestion is detecting whether the type of an object is passed in instead of its instance.
When conditionally creating subclasses, I've seen new Python developers accidentally forget to actually instantiate their objects, and linters appear to not recognize the potential faulty argument with the conditional branches; furthermore, the actual assertion error might be difficult for a young Python developer read as it would say something like `'argument <class YourClass> did not match type annotation for parameter <class YourClass>'`. The suggestion helps …
> Add suggestions section to contract checker

- python_ta/reporters/templates/stylesheet.css
This pull request modifies the error report to follow the new page design outlined in issue #730.
Changes include modifying the border radius of the error report `<section>` element and the file-name `<article>` class. 
This change was tested by displaying an error report page.
> Round corners for the error report 

- python_ta/reporters/templates/stylesheet.css
This pull request modifies the page header to follow the new page design outlined in issue #730. 
Changes include changing the text size of the title and subtitle, removing center alignment, and adjusting the padding and margin to fit the header in the top left corner of the page. 
This change was tested by displaying a report.
> Page Header Update

- python_ta/reporters/templates/stylesheet.css
This PR fixes the position of the error link text and the occurrences text as they were a bit too high after adding the svg buttons. (#730)
**Description**: Changed the line height 
PythonTA error report was rendered and changes were observed. 
Before:
After:
> Fix text positioning of the error link and occurrence heading

- python_ta/reporters/templates/stylesheet.css
This PR removes the body padding from the previous merge. (#730 ) 
**Description**: Removed body padding and updated the header element accordingly. 
Rendered an error report page to observe the change.
> Page header - remove body padding 

- python_ta/reporters/templates/script.js
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
Users may create reports for an entire directory of modules, creating an extraordinarily long report as well as table of contents. For easier navigation the table of contents lists should be collapsible.
This PR is a part of Issue #730 
1) changed current ul style to have no default bullets
2) added a clickable button at each `<li>` which both replaces the removed default bullets and toggles its parent list element.
3) added corresponding css for button and inner svg (used for the button design)
4) added button's event handlers (added both clicking, space key, and enter key handlers)
Created reports and observed elements in dev tools when activating events.
Images below
General image
Collapsing messages
Collapsing files
Focus …
> added collapse/expand buttons

- python_ta/reporters/html_reporter.py
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
This PR adds CSS styling to the table of contents. (#730)
**Description**:  
- Updated sidebar section header using the rules from the file-name header and changed the class name
- Modified font size, colour, and spacing of the text 
- Rendered a PythonTA error report to observe the changes
- Tested with different text lengths for the file name and the errors to see the fit on the table of contents
> Table of Contents Styling

- python_ta/reporters/templates/stylesheet.css
This PR adjusts the padding on the error report so that it fits better on the page (#730). 
- Added padding to `<main>`
Observed error report output 
Space at the top of the error report 
On smaller resolutions there is a better space between the error report and TOC/header
> Main Padding 

- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html
This PR adds additional text to the error link so that it is more obvious that it is clickable. (#730)
**Description**:  
- Added a `<span>` tag containing the text within the link and added styling
Rendered an error report and observed the output.
See more info text:
> Make the link to documentation more noticeable 

- python_ta/reporters/templates/template.html.jinja
This PR adds a link to the GitHub repo in the footer. 
**Description**: GitHub SVG was added which links to the PyTA repository. 
Report was generated and output observed.
> GitHub link in footer

- python_ta/contracts/__init__.py
- tests/test_contracts.py
The error messages displayed from `python_ta.contracts` has two issues that make them a bit less beginner-friendly: 
1. Type annotations are reported using their `repr`, which for most classes shows strings like `<class 'int'>` rather than what the code shows, which is just `int`.
2. Values are again reported using their `repr`, which can be very long if the objects are large (e.g., a large and/or nested collection).
1. Use a class' `name` attribute when possible. Some type annotations, like `list[int]` or the ones from `typing`, still use `repr` because that already matches the literal text in the code. Also uses `None` for the type annotation instead of `NoneType`.
2. Truncate the `repr` of values exceeding a maximum length (defaults to 20, and isn't currently …
> contracts: Make error messages more human-friendly

- python_ta/reporters/core.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html.jinja
This wraps up the redesign of the HTML report described in #730, including some updates not described there.
Notable changes are:
1. Increase overall font size.
2. Add code snippet background colour.
3. Make footer [sticky](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/), placing it at the bottom of the page.
4. Rearrange footer contents to put text on the left and logos on the right.
5. Shorten expand/collapse animation.
6. Normalize whitespace (margin and padding) around elements.
Screenshots of new look:
> html-reporter: Update styling for html report

- python_ta/reporters/html_reporter.py
Currently, our use of `BaseHTTPRequestHandler` causes a log message of the HTTP request to be printed to stderr, but this is confusing for beginners.
**Description**: Replaced the message with a more beginner-friendly one, including instructions on what to do if the page doesn't load automatically.
Tested this by running PythonTA manually, and verified that the message doesn't appear when the `output` argument is passed to `check_all`.
> html-reporter: Make server status message more user-friendly

- python_ta/__main__.py
- python_ta/reporters/core.py
- tests/fixtures/no_errors.py
- tests/test.pylintrc
- tests/test_check.py
- tests/test_examples.py
Now that we have a CLI (introduced in #683), we should report a non-zero status code when errors are detected.
**Description**: Report a non-zero exit code (currently defaults to 1) when PythonTA finds at least one error. Also introduce `--exit-zero` option (inspired by pylint) to force PythonTA to always report status code 0 instead.
Some manual testing in the terminal, and added some additional CLI tests in `test_check.py`.
> main: Report non-zero status code on errors.

- python_ta/reporters/core.py
- python_ta/reporters/json_reporter.py
The JSONReporter reports the line and column where an error starts in the text being analyzed but not the line and column where it ends. 
Both start and end positions are useful when using the output of the JSONReporter to identify problematic code.
- calculated the values of line and column endings in a new method (JSONReporter._snippet_endings)
- Added a call to JSONReporter._snippet_endings in JSONReporter.display_messages to add this info to the reported json string.
> Report last line and last column of code snippet

- docs/checkers/index.md
- examples/pylint/R1734_use_list_literal.py
Created documentation and an example for the Pylint checker R1734 use list literal.
Added R1734 example file to `examples/pylint`
Added R1734 to `index.md`
> R1734 use list literal docs #1734

- docs/checkers/index.md
- examples/pylint/R1735_use_dict_literal.py
Created documentation and an example for the Pylint checker R1735 use dict literal.
Added R1735 example file to `examples/pylint`
Added R1735 to `index.md`
> R1735 use dict literal docs #1735

- docs/checkers/index.md
- examples/pylint/W1515_forgotten_debug_statement.py
Adds the documentation for W1515 Forgotten Debug Statement as requested in the Pylint Checker Wiki page.
Added new example file (`examples/pylint/W1515_forgotten_debug_statement.py`) and a new section in the `docs/pylint/index.md` under Miscellaneous.
> W1515 forgotten debug statement docs

- .pre-commit-config.yaml
- docs/checkers/index.md
- examples/pylint/R0402_consider_using_from_import.py
Adds the documentation for R0402 Consider Using From Import as requested in the Pylint Checker Wiki page.
Added new example file (examples/pylint/R0402_consider_using_from_import.py) and a new section in the docs/pylint/index.md under Imports.
> R0402 consider using from import docs

- python_ta/patches/messages.py
- tests/test_examples.py
Previously, `test_examples.py` would not access `python_ta` and throw an error until externally installing `python_ta` due to the usage of calling Pylint via a subprocess. This PR replaces the usage of the `subprocess` module with the actual `pylint` module, which resolves the issue.
Replaced generating reports using `subprocess` by using `pylint.lint.Run`. It didn't seem like there was an option to provide a stdout string buffer so I manually replaced the system's stdout to capture the pylint report (and properly reverted the stdout).
Alternative notes:
* It might be possible to use a custom reporter as a buffer, but the approach didn't seem appealing to me.
* I considered using pylint.epylint but the method didn't seem to allow for passing in multiple files, which was the whole point of …
> Updated `tests/test_examples` to use the actual Pylint module

- .github/workflows/test.yml
Now that Python 3.10 is released, we should support it in our CI testing.
**Description**: Added Python 3.10 to CI test matrix.
> github: Add Python 3.10 to CI tests

- docs/checkers/index.md
- python_ta/__init__.py
Doc function does not link to the documentation of the checkers properly.
**Description**: First, I added header targets for every checker documentation in the `index.md` file.
Second, I updated the outdated doc function in the `python_ta/__init__.py` file to include `/checkers/index.html` in the `helper_url`.
- Build HTML from `index.md` and inspect the HTML file.
- Several calls to `doc` function. Ex: `doc("E0602")`.
> Update markdown links

- CHANGELOG.md
- docs/contracts/index.md
- python_ta/contracts/__main__.py
See #778 for an introduction to the motivation and context.
778 was closed due to the approach where decompiling the file into its AST changed the line numbers, resulting in unhelpful error tracebacks.
Added `__main__.py` for the contracts module which takes in the path to Python script to be executed as main, additional module names to be checked, and whether the main module should be checked.
Used a pseudo module to replace the main entry point for contract checking the main module
Alternatives:
- could have set checking main to be permanently false and added the pseudo module to the list of extra imports and used the cli flag to determine whether or not to add the pseudo module to the list or not
- ~~can just have one layer of execs and manually pass in the context …
> added contracts entry point

- CHANGELOG.md
- python_ta/reporters/templates/template.html.jinja
The HTML version of the report output does not link to the documentation for the specific errors.
- Check it correctly links to a specific error from the reporter generated using `python -m python_ta FILE`.
> fix html link to errors

- .pre-commit-config.yaml
I'd like to reduce the frequency of autoupdates from pre-commit.
**Description**: Switch from weekly to quarterly updates.
> pre-commit: Switch to quarterly autoupdates

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.2.0

- README.md
- docs/checkers/index.md
- examples/pylint/c0209_consider_using_f_string.py
Add example and documentation for C0209 consider using f string.
Added new example file `examples/pylint/c0209_consider_using_f_string.py` and documented it in `docs/pylint/index.md` under Code Complexity.
> C0209 add example

- docs/checkers/index.md
- python_ta/__main__.py
The links in the form `\[\]\(#[A-Z]\d{4}\)` in `docs/checkers/index.md` are no longer needed.
Removed all such links.
> Remove empty links from checkers documentation

- CHANGELOG.md
- python_ta/__main__.py
- tests/test_check.py
PythonTA can be run from the command line. However, it currently does not have a `-v/--version` flag which is popular among many command line tools.
Added `-v/--version` flag to the PythonTA CLI.
Manually confirmed `-v/--version` flags work as intended. Added unit test `test_check_version` in `tests/test_check.py`.
> Add version cli arg

- .github/PULL_REQUEST_TEMPLATE.md
- python_ta/__main__.py
Helpful reminder inspired by Markus pr template.
Add reminder to update changelog if necessary in pr checklist
> Add reminder to update changelog if necessary in pr checklist

- CHANGELOG.md
- python_ta/checkers/missing_space_in_doctest_checker.py
- python_ta/config/.pylintrc
- setup.cfg
- tests/test_custom_checkers/test_invalid_for_target_checker.py
- tests/test_custom_checkers/test_missing_space_in_doctest_checker.py
- tests/test_custom_checkers/test_possibly_undefined_checker.py
- tests/test_custom_checkers/test_redundant_assignment_checker.py
- tests/test_custom_checkers/test_shadowing_in_comprehension_checker.py
- tests/test_custom_checkers/test_unnecessary_indexing_checker.py
Updates dependencies to the latest version of astroid and pylint.
**Description**: updated to pylint v2.13 and astroid 2.11. Needed to update checker tests to pass `ignore_position=True` to the pylint helper `assertAddsMessages`, as the default behaviour changed to checking message position attributes as well.
Ran test suite and PythonTA manually.
> pylint: Upgrade to pylint 2.13 and astroid 2.11

- docs/checkers/index.md
- examples/pylint/e4702_modified_iterating_dict.py
Added Documentation and an example for the checker modified iterating dict
> Added Documentation and example for E4702 Modified iterating Dict Checker

- docs/checkers/index.md
- examples/pylint/c2503_bad_file_encoding.py
The changes made in this pull request include adding documentation of checker C2501 Bad File Encoding, along with an example that illustrates when line(s) of code in python trigger the checker and a correction to the example that demonstrates proper usage.
This pull request is required as this is one of the new checkers that got added after updating to the latest version of pylint and these changes add description to how this newly added checker works.
This pull request does not need to be tested as it is a documentation update. I did however proofread the code and documentation to make sure it aligned with the checker.
> Added documentation and example of C2501 Bad File Encoding Checker

- docs/checkers/index.md
- examples/pylint/w4701_modified_iterating_list.py
Added Documentation and an example for the checker modified iterating list
> Added Documentation and example for W4701 Modified iterating List Checker

- python_ta/contracts/__init__.py
This pull request is regarding a bug fix for a function in the contracts section. There was a bug associated with one of the variables being a tuple, but then the variable being mutated, but since it is a tuple, it cannot be mutated. Here the change was to do a reassignment instead and there was another function call which took an argument as a set, however, this variable is a tuple, so the variable was converted to a set before being passed into the other function.
This pull request is required to fix the bug associated with the function in python_ta/contracts, which is check_all_contracts(). Now the function is able to run without error, previously it ran into errors, due to one of the variables being mutated despite being a tuple.
**Description**: Did tuple reassignment and conversion …
> Fixes for contracts bug

- python_ta/checkers/forbidden_io_function_checker.py
- tests/test_custom_checkers/test_forbidden_io_function_checker.py
Modified forbidden-io-checker to differentiate between top-level functions and methods associated with classes. 
Checker did not distinguish between top-level functions and methods in classes.
Checker can now distinguish between top-level functions and dot-notation functions. 
Testing was done using different test cases on local machine.
> Modified forbidden_io_function_checker.py

- python_ta/contracts/__init__.py
Changed `tuple('__main__')` to `('__main__',)`
This pull request was done to prevent a runtime crash.
**Description**: Changed `tuple('__main__')` to `('__main__',)`
I ran `check_all_contracts` in a different file and it complied with no issues.
> tuple reassignment change

- docs/debug/index.md
- python_ta/debug/accumulation_table.py
- sample_usage/print_table.py
**Description**: Improve documentation for `python_ta.debug.accumulation_table`. Also make sure to make a shallow copy of each loop variable for storage.
Ran test suite, and additional manual testing.
> accumulation table: Improve documentation and use copy.copy for objects

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.3.0

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.3.1

- CHANGELOG.md
- python_ta/reporters/json_reporter.py
The jsonreporter parses the attributes of the the Message class. Previously this was a namedtuple but is now a dataclass. 
This PR updates the way the jsonreporter extracts these attributes from Message instances.
Tested using the markus-autotester to ensure that the needed fields are present in the json output from the jsonreporter.
> Update json reporter to work with new pylint Message class

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.3.2

- CHANGELOG.md
- python_ta/reporters/core.py
- python_ta/reporters/json_reporter.py
With the updates of pylint version, previous releases accidentally removed some old fields in the `JSONReporter`.
**Description**: Added them back in (mainly for backwards compatibility, though the `snippet` field may be useful in the future).
Ran PythonTA with the `JSONReporter` and verified that the expected fields were all there. Will add tests later on.
> reporters: Add accidentally removed fields back to json output

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.3.3!

- docs/checkers/index.md
- examples/pylint/e0643_potential_index_error.py
Added documentation for new Pylint checker E0643: Potential index error.
Added a new example file (examples/pylint/e0643_potential_index_error.py) and updated PyTa checker docs (docs/pylint/index.md) to include a description and correct example under the section Improper Python Usage.
Generated updated PyTa checker docs page with the new checker.
> Added docs for E0643: Potential index error

- .gitignore
- README.md
- docs/checkers/index.md
- examples/pylint/w0130_duplicate_value.py
Pylint added new checkers in their latest version so we needed to add documentation for them in PyTA. This pull request is only for the checker W0130: Duplicate Value.
- Added an example of the error under examples/pylint/w0130_duplicate_value.py
- Wrote an explanation of the error and provided the correct example in docs/pylint/index.md 
- Added my name to the contributor list in the README file.
Generated the documentation page to review my changes.
Question: I added an environment section to the gitignore file. Not sure if we want to have it there or if I should ignore the folder locally.
Solution: I will raise a new PR for adding the env section to gitignore file and edit documentation on setup using zsh (macOS).
> Added documentation and example of W0130 Duplicate Value

- docs/checkers/index.md
- examples/pylint/r0133_comparison_of_constants.py
Pylint added new checkers in their latest version so we needed to add documentation for them in PyTA. This pull request is only for the checker R0133: Comparison of Constants.
- Added an example of the error under r0133_comparison_of_constants.py
- Wrote an explanation of the error and provided the correct example in docs/pylint/index.md
Generated the documentation page to review my changes.
> Added documentation and example for R0133 Comparison of Constants

- CHANGELOG.md
- docs/checkers/index.md
- examples/custom_checkers/e9994_unnecessary_indexing.py
- python_ta/checkers/unnecessary_indexing_checker.py
- tests/test_custom_checkers/test_unnecessary_indexing_checker.py
The motivation behind this was to extend the functionality of Unnecessary Indexing Checker to check for unnecessary indexing in comprehensions.
I added a new visit_comprehensions method that would visit comprehension nodes and modified the helper functions written for For loops to check for the error in comprehensions as well.
I added eight new tests that check for the error in comprehensions. Four of them check for when there is no error and the other four return error messages. Some of the tests are just the comprehension version of previous tests for For loops and there are a couple that are specific to comprehensions (test_comp_incrememt_index_no_msg and test_comp_binop_msg).
> Modified unnecessary indexing checker for comprehensions

- CHANGELOG.md
- docs/checkers/index.md
- examples/custom_checkers/e9984_invalid_for_target.py
- python_ta/checkers/invalid_for_target_checker.py
- tests/test_custom_checkers/test_invalid_for_target_checker.py
The motivation was to modify invalid-for-target-checker to check for subscripting in the target of a comprehension and for loops.
I added a new visit_comprehensions method to the main checker file, added comprehension versions of all the tests in the test file, and updated the PyTa documentation and examples to include mention of comprehensions.
I added comprehension versions of all the tests that were already present in the testing file that checked for loops and then added one more that tests for slicing. I didn't add any tests that checked for edge cases in the body of the comprehension or possible if-conditions since this checker seems to only focus on the target but please let me know if those are necessary.
I noticed that …
> Modified invalid for target checker to handle comprehensions

- CHANGELOG.md
- docs/checkers/index.md
- examples/custom_checkers/e9992_top_level_code.py
- python_ta/checkers/top_level_code_checker.py
- tests/test_custom_checkers/test_top_level_code_checker.py
We would like to create a new checker called top_level_code that will flag student code when testing code is in the top level, when they could have put it inside the main block instead.  
This checker scans the statements in `module.body` and make sure the statements are one of the allowed types. The allowed types are: 
1. imports
2.  function definitions
3.  class definitions
4.  assignments to constants (ALL_CAPS variable names)
5. the main block
> Top Level Code Checker

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts.py
This made the Pyta type check stricter by raising an `AssertionError` when the expected type is `int` but got `bool` instead.
Added another condition to `check_type_strict()` that checks if the expected type is `int` and got `bool` instead. If it meets that condition, raise a `TypeError`.
I added three tests: one that checks for the correct return type `bool`, one that is expecting an `int` and got `bool`, and one that is expecting `bool` and got `int`.
> Type contracts differentiate bool and int

- python_ta/checkers/top_level_code_checker.py
- tests/test_custom_checkers/test_top_level_code_checker.py
A few small improvements to the forbidden-top-level-code checker.
**Description**: Extend the checker handle more types of assignment targets. Ensure that just the top-level statement is highlighted (rather than the entire module).
> forbidden-top-level-code checker updates

- README.md
The test suite included tests which utilized libraries that weren't listed as a dependency in the developer instructions in `README.md`.
- Added the `z3` library as a dependency in the installation instructions.
- Previewed the markdown file in PyCharm
- Used the updated command to install the dependencies, ran, and passed the tests in the test suite
> Updated dev installation instructions to include missing dependency

- .pre-commit-config.yaml
- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts.py
The `ENABLE_CONTRACT_CHECKING` constant currently only stops (some) dynamic contract checking from happening, but doesn't affect the original decorating using `@check_contracts` or `check_all_contracts`.
**Description**: Modify  `@check_contracts` and `check_all_contracts` so that they simply return the original function/class unchanged if `ENABLE_CONTRACT_CHECKING = False`.
> contracts: Make ENABLE_CONTRACT_CHECKING=False skip initial decoration

- CHANGELOG.md
- docs/checkers/index.md
- examples/custom_checkers/e9950_forbidden_python_syntax.py
- python_ta/checkers/forbidden_python_syntax_checker.py
- tests/test_custom_checkers/test_forbidden_python_syntax_checker.py
Certain Python elements may be disallowed for use on assessments so this checker is being created to report on them.
- Created `ForbiddenPythonSyntaxChecker` which reports on any use of disallowed Python elements (e.g. `for` loops aren't being allowed for this assignment)
- Created test suite to check if the checker correctly reports (or ignores) Python syntax that has been disallowed (allowed)
- Created an example for this checker
- Updated the PyTA documentation to document this new checker
- Updated the CHANGELOG.md file to include this checker
- Ran the test suite (along with pre-existing tests) in the command line and verified that they've passed
- Ran the following commands in Python to connect `pyta` with the new checker …
> Created ForbiddenPythonSyntaxChecker and its associated test suite

- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_label_if.py
Currently, the use of CFGs in PyTA is limited to checkers. This change should hopefully be the start of allowing them to be used for educational purposes.
- Augmented the CFGEdge class to have a `label` attribute that is used to label each edge in the graph.
- Modified the `visit_if` method to label the edges transitioning from the if condition.
- Modified `create_block` and `link_or_merge` to include optional arguments for passing the edge label.
- Added some tests to check whether labels were updated correctly.
- Ran the test suite and verified all tests passed.
- Created some CFGs using `draw_cfg` and made sure the changes didn't break anything.
- Ran a modified version of `draw_cfg` with the debugger and verified that the …
> Augmented CFG-related classes to support labelling edges

- setup.cfg
Tests on GitHub are failing despite being completely unrelated to the changes made.
- Updated `setup.cfg` to add the constraint `< 3` for typeguard
> Updated typeguard constraint in setup.cfg

- python_ta/cfg/visitor.py
- tests/test_cfg/test_if.py
The CFGs produced aren't that user friendly because if conditions would get merged with preceding statements. Although the statements are still executed in sequence, it may be misleading so add an option to configure the visitor to not merge the condition with the previous statements.
- Added an `options` dict to the `CFGVisitor` class which may be passed into the initializer to prevent merging if conditions with preceding statements.
- Added new test cases to verify that, when configured to do so, a new block is created to separate the if condition from preceding statements.
- Ran the test suite and verified all the test cases passed.
- Verified the newly added test cases passed.
- Verified that the CFGs produced from …
> Updated CFGVisitor with an options attribute to configure the visitor

- CHANGELOG.md
- setup.cfg
Pin dependencies to avoid accidentally allowing breaking changes from dependencies.
Ran test suite and ran PythonTA manually.
> deps: Pin dependencies

- python_ta/cfg/visitor.py
- sample_usage/draw_cfg.py
- tests/test_cfg/test_label_while.py
In the current state, the cfgs that pyta produces are not that easily consumable. These changes aim to make the cfg and the control flow of their program easily understandable by the viewer.
- Changed the output file format of the cfg to `.svg` so that it can be rescaled without decreasing the image's resolution.
- Added labels for edges coming out of the while loop test condition.
- Added new test cases to verify that the labels have been added properly.
- Ran the test suite and verified all tests passed
- Added new test cases to verify that the labels were correctly added
- Generated a CFG with a sample code snippet and verified that the labels have been added
> Make the cfgs pyta produces more prettier

- .github/workflows/test.yml
The current testing environment does not have the `graphviz` library installed but tests added in #895 require this library to run.
- Updated the GitHub actions config file to now install `graphviz` as a dependency
- Ran the test suite and verified all tests passed
- ~~In the exact task that was sent on Slack, you mentioned "You'll need to learn about how to install Ubuntu dependencies from this config file". What did you mean by this? Was there something else that I missed here?~~
> Added graphviz library as dependency to test environment

- docs/checkers/index.md
- examples/pylint/w0719_broad_exception_raised.py
Checker W0719 (broad-exception-raised) is one of the new checkers that recently got added to PythonTA. The changes made in this pull request provide a description for checker W0719 to ensure informed and proper usage.
**Description**: Added documentation of checker W0719 (broad-exception-raised), created an example to display how error W0719 is triggered, and provided a correction to the example code that demonstrates how to resolve error W0719.
Used a pylint scanner to ensure the example code emits and the correction resolves error W0719. Proofread the documentation of checker W0719 to ensure that the explanation is beginner-friendly and correct.
> Added documentation and example of W0719 Broad Exception Raised Checker

- .coveragerc
- .github/workflows/test.yml
- setup.cfg
I reviewed the current coveralls integration and made updates based on the latest pytest-cov release (v4.0.0).
- Updated `pytest-cov` dependency to `~= 4.0.0`
- This enabled the `lcov` coverage file format, which allows us to use the [Coveralls GitHub Action](https://github.com/marketplace/coveralls) instead of the `coveralls` Python package
- Removed the `python_ta/debug/` folder from the coverage report, since we can't run tests with coverage on that submodule.
- Updated to actions/checkout@v3 (to fix Node deprecation warning)
Checked that the CI integration with Coveralls works correctly on this pull request.
> Update coveralls integration

- sample_usage/draw_cfg.py
`python_ta/cfg/cfg_generator.py` essentially uses the same code as `sample_usage/draw_cfg.py` (except for a few minor changes). This PR serves to reduce code smell by removing the duplicate code and using the `python_ta` API to fulfill the functionality of `sample_usage/draw_cfg`.
~~**NOTE:** this depends on the changes in #904~~ `git rebase` completed.
- Updated `sample_usage/draw_cfg.py` to import from `python_ta.cfg` instead of using duplicate code.
- Ran the test suite locally and ensured that all test cases passed.
- Followed the usage instructions in `sample_usage/draw_cfg.py` to create some control flow graphs to verify that they are still correctly being produced.
- ~~Do not merge until #904 is merged and a `git rebase` …
> Update sample_usage/draw_cfg to use the pyta API to create CFGs

- .github/workflows/test.yml
- CHANGELOG.md
- README.md
- docs/cfg/index.md
- examples/sample_usage/draw_cfg.py
- pyproject.toml
- python_ta/cfg/__init__.py
- tests/test_cfg/test_cfg_generator.py
Currently there is an error when importing `python_ta` if `graphviz` isn't installed, despite our intention of making it an optional dependency.
**Description**: Fixed `python_ta.cfg` (which is used in `python_ta.check_all`) to no longer import `generate_cfg`. Instead, users will need to explicitly import `python_ta.cfg.cfg_generator` to access `generate_cfg`.
Tested to ensure `graphviz` is no longer required for `python_ta` to be imported.
> Make graphviz an optional dependency

- README.md
- docs/checkers/index.md
Some custom checkers have options that augment the behavior of the checker, one of them being the pycodestyle_checker. Currently, there is no documentation describing the effect and use of pycodestyle_checker's option: pycodestyle-ignore. The purpose of this pull request is to add that information to the checker's documentation.
**Description**: Added documentation describing the effect and use of pycodestyle_checker's option: pycodestyle-ignore. Documentation includes example of use. 
To test that the documentation changes registered, I used Sphinx to build the documentation into an html file, and checked if the changes appeared correctly. To confirm that the code snippet was correct, I tested pyta on a local file twice. Once with the config in …
> Pycodestyle options docs

- CHANGELOG.md
- python_ta/checkers/pycodestyle_checker.py
Currently, the `PycodestyleChecker`, which is used to check the PEP8 style conventions, does not display the pycodestyle error codes in the HTML file generated. This pull request adds the error codes reported by pycodestyle to the error messages displayed by PythonTA.
**Description**: The method `get_file_results` is used to get the results from the `StandardReport` class, which contains all the information about the pycodestyle checks on a given module. Previously, the error code was returned but unused. In my changes, I store the error code in a variable and add it to the error message to be displayed.
I tested my changes by checking the message displayed in the HTML report produced after running
```
import python_ta
python_ta.check_all()
``` …
> Added pycodestyle error code to the error message in pycodestyle_checker

- examples/nodes/async_function_def.py
- examples/nodes/class_def.py
- examples/nodes/function_def.py
- examples/nodes/module.py
- examples/nodes/yield_from.py
Starting form version 3.0.0, `astroid` substituted the deprecated `doc` attribute (a `str` object) from the `FunctionDef`, `ClassDef` and `Module` nodes, with a new attribute `doc_node` (a `Const` object). This pull request reflects this change in the PythonTA documentation.
In the example nodes `function_def.py`, `class_def.py`, and `module.py` example file, I changed the attribute `doc` to `doc_node`, and updated the type consistently, both in the attribute description and in the example usage. Then, since the `yielf_from.py` and `async_function_def.py` have example usages of the `FunctionDef` node, I updated the example usage as well to reflect the change.
I did not test this pull request, since it only includes documentation …
> Update nodes documentation to include doc_node instead of doc

- python_ta/debug/snapshot.py
- tests/test_debug/test_accumulation_table.py
Currently, our process for extracting snapshot data does not align seamlessly with the requirements of our `memory-models-rough` library. This discrepancy hinders our ability to leverage snapshot data effectively within memory models, limiting the potential insights and optimizations we can achieve. To bridge this gap, we propose the development and integration of a new function, `snapshot_to_json`, specifically designed to convert snapshot outputs into a JSON format that is directly consumable by the memory-models-rough module. This initiative not only aims to streamline our data processing pipeline but also enhances the synergy between different components of our system, unlocking new possibilities for data analysis and model performance. We have segmented this task into three distinct …
> snapshot_to_json step1

- CHANGELOG.md
- pyproject.toml
Closes #1019 and closes #1020
**Description**: updated pylint and astroid versions.
Manual testing and ran test suite.
> Update to pylint v3.1

- python_ta/debug/snapshot.py
- tests/test_debug/test_accumulation_table.py
In earlier phases of our project, we successfully implemented the functionality to extract and convert simple (i.e. primitive) data types from both local and global scopes within a Python module into a JSON format. This was primarily designed to integrate with the `memory-models-rough` library, which assists in visualizing Python's memory models. Following this initial success, our current focus shifts towards enhancing the scope of our tool to handle more complex data structures, specifically targeting Python's compound data types: lists, sets, dictionaries, and tuples.
This PR represents a significant step forward in our project's development. It introduces comprehensive support for these compound data types, which are crucial for a wide array of programming tasks in Python. By …
> Snapshot step 2

- python_ta/debug/snapshot.py
- tests/test_debug/test_accumulation_table.py
This pull request introduces changes aimed at enhancing the codebase by  implementing a feature that supports user-defined class serialization. The motivation behind these changes is to facilitate a new functionality that allows capturing snapshots of user-defined classes, aiding in debugging processes.
- Implemented functionality in the `snapshot_to_json` method to support the serialization of user-defined classes, including handling of nested user-defined class instances.
- Created unit tests to verify the correct serialization of user-defined classes, both with primitive attributes and nested user-defined class attributes.
The changes have been tested through the addition of new unit tests that specifically target the new …
> Extending snapshot for user-defined classes

- CHANGELOG.md
- python_ta/cfg/visitor.py
- python_ta/contracts/__init__.py
- tests/test_cfg/test_functions_preconditions.py
The CFG visitor creates a new CFG for any function blocks encountered. Assuming we are checking preconditions, these blocks would only be ran if the preconditions are satisfied. Thus, the initial edge in these function CFGs now stores the preconditions of the function, as an `and` node in the condition attribute of the edge. 
Created helper function to extract preconditions, combine them into an `and` expression, and parse into AST node
Used helper function to set CFGEdge condition in the initial function CFG edge to store the condition node
Allowed `parse_arguments` from contracts to take in AST function definition nodes with no docstring
Created tests to verify conditions were set properly
Implemented tests to ensure condition …
> Added function preconditions to initial function CFG edge

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
This pull request makes a few changes to the current pull request templates.
1. Merge the "Motivation and Context" and "Description of Changes" sections, since those were often blurred.
2. Add an explicit place for screenshots.
3. Change the "type of change" from a task list into a table, to avoid having to delete unnecessary items.
4. Add two new change types, "Dependency" and …
> Update pull request template and changelog format

- CHANGELOG.md
- README.md
Updated parts of the `README.md` that specify now-defunct paths to reflect the current folder and file structure of the project.
<details>
</details>
| ♻️ _Refactoring_ (internal change to codebase, without changing …
> Update defunct paths in README

- .github/workflows/test.yml
- CHANGELOG.md
Modified GitHub Actions workflow config file to allow tests to run on draft PRs.
<details>
</details>
| ♻️ _Refactoring_ …
> Allow tests to run on draft PRs

- CHANGELOG.md
- examples/sample_usage/draw_cfg.py
- examples/sample_usage/print_ast.py
Update usage message in `examples/sample_usage/draw_cfg.py` and `examples/sample_usage/print_ast.py` to be correct on all operating systems.
Previously, the usage message specifies `python` as the executable to use, however on MacOS it should say `python3`. Using two small imports, this can be generalized so that the usage message is most useful to developers on all operating systems. …
> Update usage messages in examples/sample_usage module

- CHANGELOG.md
- python_ta/cfg/visitor.py
Fix minor typo in `CFGVisitor` class.
| ♻️ _Refactoring_ (internal change to codebase, without changing functionality)          |          |
| 🚦 _Test update_ (change that _only_ adds or …
> Fix typo in CFGVisitor

- CHANGELOG.md
- tests/test_examples.py
Remove entirely redundant extra variable from `tests/test_examples.py::test_examples_files_pyta`.
| ♻️ _Refactoring_ (internal change to codebase, without changing functionality) …
> Remove Redundant Line in test_examples.py

- CHANGELOG.md
- pyproject.toml
Currently trying to run `pip` commands after installing the pre-commit hooks results in an error:
```
setuptools.errors.PackageDiscoveryError: Multiple top-level packages discovered in a flat-layout: ['python_ta', 'node_modules'].
```
This PR modifies our `pyproject.toml` file to exclude the `node_modules` folder.
<details> …
> Exclude node_modules/ from package autodiscovery

- CHANGELOG.md
- python_ta/cfg/cfg_generator.py
- python_ta/cfg/graph.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_label_if.py
- tests/test_cfg/test_label_while.py
Add a new attribute `negate` to CFGEdge to indicate whether the condition is being negated on the edge. This attribute is used for creating edge Z3 constraints and rendering graph.
...
<details>
</details>
| 🐛 _Bug fix_ …
> refactor: Add `negate` Attribute to `CFGEdge`

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/test_snapshot.py
- Add an optional filter `include` to `snapshot` to only capture variables in specified frames
- Use `repr` to serialize certain unserializable values (e.g. `PosixPath`)
...
| ✨ _New feature_ (non-breaking change that adds functionality)                          |      x    |
| 🐛 _Bug fix_ (non-breaking change that fixes an issue)                                  |    x      |
| ♻️ …
> Add an optional filter to `snapshot` for frames to include and fix unserializable values

- CHANGELOG.md
- tests/test_custom_checkers/test_one_iteration_checker.py
Implement unit tests for `one-teration-checker`
...
<details>
</details>
| …
> Create unit tests for one-iteration-checker

- CHANGELOG.md
- python_ta/checkers/redundant_assignment_checker.py
- tests/test_custom_checkers/test_redundant_assignment_checker.py
Add checking for `AnnAssign` node in `redundant_assignment_checker`
...
<details>
</details>
| …
> Add checking for annotated assignment in `redundant_assignment_checker`

- .github/workflows/test.yml
- CHANGELOG.md
- pyproject.toml
- python_ta/__init__.py
- python_ta/utils.py
- tests/test_contracts/test_contracts.py
- tests/test_debug/test_snapshot.py
- tests/test_init_logging.py
Closes #1079 and closes #1092 by upgrading pylint and astroid to v3.3. This also adds support for Python 3.13 and drops support for Python 3.8.
I updated a few places in the code that were doing manual version checks that are now no longer necessary.
<details>
</details>
_(Write an `X` or a brief description next to the type …
> Update to pylint and astroid v3.3, add support for Pyton 3.13, and drop support for Python 3.8

- CHANGELOG.md
- docs/contracts/index.md
- python_ta/contracts/__init__.py
- tests/conftest.py
- tests/test_contracts/test_contracts.py
resolves #958. Added a `STRICT_NUMERIC_TYPES` configuration to `python_ta.contracts` allowing to enable/disable stricter type checking of numeric types, as per the request within the issue. By default, this configuration is set to `True`, which enables strict checking. Consider the following example below.
```
from python_ta.contracts import check_contracts
@check_contracts
def foo(a: …
```
> Added a STRICT_NUMERIC_TYPES configuration to `python_ta.contracts`

- CHANGELOG.md
- python_ta/cfg/visitor.py
- tests/test_cfg/test_functions_preconditions.py
This fixes a bug in PythonTA, illustrated by the following example:
```python
def f(x: int) -> int:
"""
Preconditions:
-
- x > 0
"""
return x
```
The first `-` is parsed as a blank precondition, which raises a `ValueError` at this line: https://github.com/pyta-uoft/pyta/blob/master/python_ta/cfg/visitor.py#L492.
This pull request fixes this bug by handling the `ValueError`.
<details> …
> Fixed issue where empty preconditions were preventing CFGs from being generated

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts/test_contracts.py
This PR enhances the @check_contracts decorator by extending strict numeric type checking across the entire numeric hierarchy, including support for complex numbers. Additionally, it introduces strict type validation for nested and union types, such as list[int], dict[float, int], and Union[int, float]. In the current behaviour, no error will be rasied, as in the example below.
``` …
```
> Enable Strict Type Checking for Complex Data Types in check_contracts

- CHANGELOG.md
- python_ta/cfg/graph.py
- python_ta/checkers/one_iteration_checker.py
- tests/test_custom_checkers/test_one_iteration_checker.py
Add `z3` option to `one-iteration-checker` to ignore unfeasible nodes based on edge z3 constraints. 
Based on z3 constraints, the `one-iteration` error message would not be reported if:
1. The loop statement is unfeasible.
2. The loop condition is unsatisfied when it is first entered, leading to zero iterations.
The `one-iteration` error message will be reported if:
1. A conditional …
> One iteration checker z3 option

- .github/workflows/publish.yml
- CHANGELOG.md
This pull requests follows [this guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows) to enable automated publishing of the PythonTA package to PyPI after making a new release.
Note: unlike the guide, which triggers the publishing after creating a tag, this configuration triggers it after making a new [GitHub …
> Added GitHub Action workflow for automatically publishing releases to PyPI

- CHANGELOG.md
- python_ta/__init__.py
Release for v2.9.0.
<details>
</details>
| ----------------------------------------------------------------------------------- …
> Release v2.9.0!

- CHANGELOG.md
- MANIFEST.in
This pull request adds the static files in `python_ta/debug/webstepper` to `MANIFEST.in`, which ensures they're included in the distributed package.
<details>
</details>
| Type …
> Added python_ta/debug/webstepper to project MANIFEST.in

- CHANGELOG.md
- python_ta/__init__.py
Release for v2.9.1. This includes the fix in https://github.com/pyta-uoft/pyta/pull/1124.
> Release v2..9.1!

- .github/workflows/test.yml
- CHANGELOG.md
- tests/conftest.py
- tests/test_examples.py
Configure CI tests to run on `base` (`z3-solver` uninstalled) and `z3-solver` (`z3-solver` installed).
Add `--exclude-z3` Pytest command-line argument to exclude test suites dependeing on `z3-solver`
...
<details>
</details>
| …
> Z3 depdendency check ci

- CHANGELOG.md
- python_ta/checkers/redundant_assignment_checker.py
- tests/test_custom_checkers/test_redundant_assignment_checker.py
Currently the `redundant-assignment` check flags annotation-only assignment statements, e.g. `x : int`. These should be ignored by the check.
<details>
</details>
| Type …
> Ignore annotation-only assignment statements in redundant-assignment check

- CHANGELOG.md
- python_ta/__init__.py
> Release v2.9.2!

- CHANGELOG.md
- python_ta/__init__.py
- python_ta/checkers/redundant_assignment_checker.py
- tests/test_custom_checkers/test_redundant_assignment_checker.py
Updates the master branch with changes from the 2.9.2 release.
<details>
</details>
| …
> v2.9.2 update

- .github/workflows/test.yml
- CHANGELOG.md
This requires using `matrix.dependency` as part of the `flag-name` when tests are uploaded to coveralls.
<details>
</details> …
> Configured CI to upload coverage report for both base and z3 test environments

- CHANGELOG.md
- docs/checkers/index.md
- docs/usage/configuration.md
- python_ta/checkers/static_type_checker.py
- python_ta/config/.pylintrc
- tests/test.pylintrc
- tests/test_custom_checkers/test_static_type_checker.py
Added a new checker option `mypy-options` in StaticTypeChecker to let users override the default mypy command-line arguments passed to the checker.
...
<details>
</details>
| Type …
> Add mypy-options to StaticTypeChecker

- CHANGELOG.md
- docs/usage/configuration.md
This pull requests adds documentation for customizing error messages.
<details>
</details>
| …
> Add documentation for error message configuration

- CHANGELOG.md
- python_ta/checkers/pycodestyle_checker.py
- python_ta/checkers/static_type_checker.py
Previously, `PycodestyleChecker` and `StaticTypeChecker` were calling `node.stream()` but not explicitly closing the stream, which caused warnings to be reported. The calls to `node.stream()` were unnecessary, and the information required could be accessed directly from the `Module` node.
<details>
</details>
_(Write an `X` …
> Remove node.stream() calls in raw file checkers

- CHANGELOG.md
- python_ta/contracts/__init__.py
- tests/test_contracts/test_class_contracts.py
- tests/test_contracts/test_contracts.py
This PR makes two updates:
1. Improve error message clarity and make the wording consistent across the different messages
2. Fixes a bug where if a class instance had an attribute reassigned to an invalid value in a top-level statement, the old value of the attribute would not be restored.
<details>
</details>
_(Write an `X` …
> Improve check_contracts error messages and fix setattr bug

- CHANGELOG.md
- python_ta/__init__.py
- tests/test_init_logging.py
This pull request changes two `check_all` messages (reporting the configuration file used and the messages configuration file used) to `logging.debug`, causing them to be hidden by default.
<details>
</details>
| Type …
> Move check_all configuration info to logging DEBUG level

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/test_snapshot.py
This pull request makes `None` values processed by `snapshot_to_json` compatible with MemoryViz.
<details>
</details>
| …
> Fixed svg rendering of None in snapshot

- CHANGELOG.md
- python_ta/debug/snapshot.py
- tests/test_debug/test_snapshot.py
This reverts commit 68e5c57ebcdc1aff8acb3ea09fadea807253e4a3.
This reverts a previous commit to use deep copying in the `snapshot` function. We can't do this (yet) because `snapshot_to_json` relies on aliases in order to generate "ids" for visualization. So if we want to do deep copying, we need to track the aliasing separately, or merge `snapshot_to_json` into `snapshot` so that the …
> Revert "Ensure snapshot returns deep copies rather than object aliases"

- CHANGELOG.md
- python_ta/cfg/__init__.py
This fixes an issue in the 2.10 release where if graphviz wasn't installed, `import python_ta` failed.
<details>
</details>
| …
> Fix import error when graphviz is not installed

- CHANGELOG.md
- python_ta/__init__.py
> Release 2.10.1

- CHANGELOG.md
- docs/usage/configuration.md
- python_ta/__init__.py
- python_ta/__main__.py
- python_ta/config/.pylintrc
- python_ta/reporters/color_reporter.py
- python_ta/reporters/html_reporter.py
- python_ta/reporters/json_reporter.py
- python_ta/reporters/plain_reporter.py
- tests/test.pylintrc
- tests/test_black.py
- tests/test_check.py
- tests/test_config/file_fixtures/test_f0011.pylintrc
- tests/test_config/file_fixtures/test_json_with_errors.pylintrc
- tests/test_config/file_fixtures/test_plain_with_errors.pylintrc
- tests/test_config/file_fixtures/test_with_errors.pylintrc
- tests/test_config/test_num_error_occurrences.py
- tests/test_examples.py
- tests/test_init_logging.py
- tests/test_main.py
- tests/test_messages_config/test_no_user_config_no_pyta_overwrite.pylintrc
- tests/test_messages_config/test_no_user_config_pyta_overwrite.pylintrc
- tests/test_messages_config/test_user_config_incorrect_section_header.pylintrc
- tests/test_messages_config/test_user_config_no_pyta_overwrite.pylintrc
- tests/test_messages_config/test_user_config_no_section_header_incorrect_error_message.pylintrc
- tests/test_messages_config/test_user_config_no_section_header_no_pyta_overwrite.pylintrc
- tests/test_messages_config/test_user_config_no_section_header_pyta_overwrite.pylintrc
- tests/test_messages_config/test_user_config_pyta_overwrite.pylintrc
Accepting reporter aliases in the `output-format` config option in place of the full reporter plugin path.
I also updated all references to use the new shorthand.
...
<details>
</details>
| Type …
> Accept Reporter Aliases in `output-format` Config Option

- CHANGELOG.md
- README.md
- python_ta/check/helpers.py
- tests/test_check.py
Made 2 **key changes**:
1) Added a test case to `test_check.py` for better code coverage in `get_valid_files_to_check()` helper in `helpers.py`
2) Removed unreachable code in `get_valid_files_to_check()`
As said above, I added a test case that verifies if `check_all()` works with package notation, and hence increasing the code coverage in `get_valid_files_to_check()`.
As for number 2, after carefully debugging and reading documentation, I realized that an `else` branch was unreachable, thus explaining why there was no coverage. 
It turns out that `modutils.file_from_modpath(item.split("."))` would always cause an **ImportError** if the package path (dot notation) was wrong. Hence, the if statement `if os.path.exists(filepath)` would always be true, since the produced path **HAD** to exist …
> Issue coverage

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
I have linked the contributions list (README.md) in the pull request template, helping new developers to locate the list of contributors more quickly
<details>
</details>
| 🐛 _Bug fix_ (non-breaking change that fixes an issue) …
> Linked Contributors List (README.md) to Pull Request Template

- CHANGELOG.md
- README.md
- python_ta/transforms/z3_visitor.py
- tests/test_cfg/test_z3_constraints.py
- tests/test_z3_visitor.py
Fixes #1062
This pull request updates set_function_def_z3_constraints in z3_visitor.py to simplify the combined Z3 preconditions using z3.simplify(z3.And(...)).
Previously, each precondition was stored individually. This change combines and simplifies them into a single Z3 expression, improving efficiency and logical clarity.
Also updates the README and CHANGELOG files to reflect this change.
...
<details>
</details>
| 🚨 …
> Simplify Combined Z3 Preconditions in z3_visitor.py Using z3.simplify

- CHANGELOG.md
- python_ta/cfg/cfg_generator.py
- python_ta/cfg/visitor.py
- tests/test_cfg/test_match.py
Added support for `match` statements when generating the CFG. 
> separate-condition-blocks : True
> separate-condition-blocks : False
<details>
</details>
| Type …
> Added CFG parsing for the match statement

- CHANGELOG.md
- python_ta/reporters/templates/script.js
- python_ta/reporters/templates/stylesheet.css
- python_ta/reporters/templates/template.html.jinja
- tests/test_reporters/snapshots/test_html_server/test_no_watch_server_is_non_persistent/no_watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_persistence/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot_updated.html
*(Describe your changes here. Also describe the motivation for your changes: what problem do they solve, or how do they improve the application or codebase? If this pull request fixes an open issue, [use a keyword to link this pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).)*
This PR adds dark/light mode support to the PythonTA HTML report with automatic system preference detection.
**Changes:**
- Added CSS custom properties for all colors to enable theming
- Implemented light (default) and dark color schemes
- Added a theme toggle button in the sidebar header (next to "Table of Contents") with sun/moon icons
- Dark mode uses VS Code's syntax highlighting …
> Added Dark Mode to PythonTA Web Reporter

- CHANGELOG.md
- python_ta/reporters/templates/stylesheet.css
- tests/test_reporters/snapshots/test_html_server/test_no_watch_server_is_non_persistent/no_watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_persistence/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot_updated.html
Updated the color palette for the PythonTA web reporter to improve readability and visual hierarchy. Changed to a high-contrast professional theme with blue accents for better visual impact.
| ✨ _New feature_ (non-breaking change that adds functionality)                          |       x   |
| 🐛 _Bug fix_ (non-breaking change that fixes an issue)                                  | …
> Improve Colours for both HTML Reporter Light and Dark Themes

- CHANGELOG.md
- python_ta/reporters/templates/stylesheet.css
- tests/test_reporters/snapshots/test_html_server/test_no_watch_server_is_non_persistent/no_watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_persistence/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot.html
- tests/test_reporters/snapshots/test_html_server/test_watch_update/watch_html_server_snapshot_updated.html
Currently, the dark theme had inconsistent colors with the light theme: --text-secondary used clashing light blue, and error title colors were orange/cyan rather than red/blue.
Thus, I updated three dark theme color variables:
--text-secondary: 
#9cdcfe → #e8e8e8
--code-error: 
#f48771 → #ed5968
--style-error: 
#4fc1ff → #4d86dc
Improves consistency with light theme palette while maintaining accessibility
Before the change:
After the change:
| 🚨 _Breaking change_ (fix or feature that would …
> Update Error Type Text Colors to Be Consistent Across Themes

- CHANGELOG.md
- python_ta/debug/snapshot.py
The update to using interactivity in MemoryViz v0.7.0 isn't compatible with the Webstepper (something about how the script tags are being parsed, likely). This PR adds the `--no-interactive` flag to disable interactivity when generating the SVG files, and pins the default MemoryViz version to prevent future updates from accidentally breaking `snapshot`'s behaviour.
<details> …
> Fixed SnapshotTracer compability with MemoryViz v0.7.0

- .github/workflows/test.yml
- CHANGELOG.md
This PR updates Node to v24 in our GitHub Actions.
<details>
</details>
| …
> Updated GitHub Actions workflow to Node 24

- CHANGELOG.md
- python_ta/checkers/pycodestyle_checker.py
- python_ta/reporters/node_printers.py
- tests/test_custom_checkers/test_pycodestyle_checker.py
Updated the format of the Pycodestyle error messages rendered by pycodestyle_checker.py module to be more concise and to remove irrelevant information that the students might not care about. See screenshots for a before and after comparison.
...
<details>
Before:
After:
</details>
| ✨ _New feature_ (non-breaking change that …
> Updating error message format 
